import { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';

export type Language = 'es' | 'fr';

export interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traducciones básicas de la aplicación
const translations = {
  es: {
    // Navegación
    'nav.sales': 'Ventas',
    'nav.inventory': 'Inventario',
    'nav.finance': 'Finanzas',
    'nav.system': 'Sistema',
    'nav.floor': 'Sala',
    'nav.pos': 'Punto de Venta',
    'nav.orders': 'Órdenes',
    'nav.products': 'Productos',
    'nav.categories': 'Categorías',
    'nav.users': 'Usuarios',
    'nav.cash': 'Caja',
    'nav.time-tracking': 'Tiempo Empleados',
    'nav.suppliers': 'Proveedores',
    'nav.expenses': 'Gastos',
    'nav.analytics': 'Analíticas',
    'nav.role-management': 'Gestión de Roles',
    'nav.company-settings': 'Información Empresa',
    'nav.app-settings': 'Configuración',

    // Acciones comunes
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.add': 'Agregar',
    'common.search': 'Buscar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',

    // Configuración
    'settings.language': 'Idioma',
    'settings.language.es': 'Español',
    'settings.language.fr': 'Francés',
    'settings.language.description': 'Selecciona el idioma de la aplicación',
    'settings.general': 'Configuración General',
    'settings.general.description': 'Personaliza el comportamiento de la aplicación',
    'settings.theme': 'Tema',
    'settings.theme.light': 'Claro',
    'settings.theme.dark': 'Oscuro',
    'settings.theme.auto': 'Automático',

    // Mensajes
    'messages.language-changed': 'Idioma cambiado correctamente',
    'messages.settings-saved': 'Configuración guardada correctamente',

    // Estado de conexión
    'Available': 'Disponible',
    'Not available': 'No disponible',
    'Status changed to: Available': 'Estado cambiado a: Disponible',
    'Status changed to: Not available': 'Estado cambiado a: No disponible',
    'Click to mark yourself as unavailable': 'Haz clic para marcarte como no disponible',
    'Click to mark yourself as available': 'Haz clic para marcarte como disponible',
    'connected': 'se conectó',
    'disconnected': 'se desconectó',

    // Notificaciones
    'cerró caja': 'cerró caja',
    'abrió caja': 'abrió caja',
    'Pedido': 'Pedido',
    'eliminado por': 'eliminado por',
    'completado por': 'completado por',

    // Configuración empresa
    'Información de la Empresa': 'Información de la Empresa',
    'Configure los datos que aparecen en tickets y reportes': 'Configure los datos que aparecen en tickets y reportes',
    'Esta información aparecerá en:': 'Esta información aparecerá en:',
    'Todos los tickets de venta impresos': 'Todos los tickets de venta impresos',
    'Reportes Excel exportados desde Analíticas': 'Reportes Excel exportados desde Analíticas',
    'Reportes de tiempo de empleados': 'Reportes de tiempo de empleados',
    'Cualquier documento generado por el sistema': 'Cualquier documento generado por el sistema',
    'Nombre de la Empresa': 'Nombre de la Empresa',
    'Dirección': 'Dirección',
    'Número de Teléfono': 'Número de Teléfono',
    'Guardar Cambios': 'Guardar Cambios',
    'Deshacer': 'Deshacer',
    'Vista Previa (Tickets)': 'Vista Previa (Tickets)',
    'Información de pedido...': 'Información de pedido...',
    'Este nombre aparecerá en todos los documentos': 'Este nombre aparecerá en todos los documentos',
    'Dirección física de la empresa': 'Dirección física de la empresa',
    'Número de contacto para clientes': 'Número de contacto para clientes',

    // Sistema de Gestión
    'Sistema de Gestión': 'Sistema de Gestión',
    'Menú de Navegación': 'Menú de Navegación',
    'Menú Admin': 'Menú Admin',
    'Salir': 'Salir',
    'Cerrar Sesión': 'Cerrar Sesión',
    'Sala': 'Sala',
    'Pedidos': 'Pedidos',
    'Punto de Venta': 'Punto de Venta',
    'Apertura de Caja': 'Apertura de Caja',
    'Indique el monto inicial en caja para comenzar su turno.': 'Indique el monto inicial en caja para comenzar su turno.',
    'Cierre de Caja': 'Cierre de Caja',
    'Indique el monto final en caja antes de cerrar sesión.': 'Indique el monto final en caja antes de cerrar sesión.',

    // POS - Punto de Venta
    'Cargando productos...': 'Cargando productos...',
    'Reintentar': 'Reintentar',
    'Todos': 'Todos',
    'Agregar': 'Agregar',
    'Agregar al carrito': 'Agregar al carrito',
    'Cargar más productos': 'Cargar más productos',
    'Carrito de Compras': 'Carrito de Compras',
    'El carrito está vacío': 'El carrito está vacío',
    'Selecciona productos para comenzar': 'Selecciona productos para comenzar',
    'Para llevar': 'Para llevar',
    'En sala': 'En sala',
    'Seleccione mesa': 'Seleccione mesa',
    'Confirmar Pedido': 'Confirmar Pedido',
    'Seleccionar Método de Pago': 'Seleccionar Método de Pago',
    'Efectivo': 'Efectivo',
    'Pago en efectivo': 'Pago en efectivo',
    'Tarjeta': 'Tarjeta',
    'Pago con tarjeta': 'Pago con tarjeta',
    'Digital': 'Digital',
    'Pago digital': 'Pago digital',
    'Cancelar': 'Cancelar',
    'Total del Pedido:': 'Total del Pedido:',
    'Método de Pago:': 'Método de Pago:',
    'Después': 'Después',
    'Validar e Imprimir': 'Validar e Imprimir',

    // Sala - Room Management
    'Gestión de Sala': 'Gestión de Sala',
    'Sala': 'Sala',
    'Cargando mesas...': 'Cargando mesas...',
    'No se pudieron cargar las mesas': 'No se pudieron cargar las mesas',
    'Error al cargar mesas': 'Error al cargar mesas',
    'Se agregaron 6 mesas por defecto': 'Se agregaron 6 mesas por defecto',
    'No se pudieron agregar las mesas (requiere rol admin)': 'No se pudieron agregar las mesas (requiere rol admin)',
    'No se pudieron cargar los pedidos de la mesa': 'No se pudieron cargar los pedidos de la mesa',
    'Mesa seleccionada para la orden': 'Mesa seleccionada para la orden',
    'No se pudo verificar el estado de la mesa': 'No se pudo verificar el estado de la mesa',
    'Seleccione una mesa primero': 'Seleccione una mesa primero',
    'Pedido validado correctamente': 'Pedido validado correctamente',
    'No se pudo validar el pedido': 'No se pudo validar el pedido',
    'Orden marcada como para llevar': 'Orden marcada como para llevar',
    'Mesa seleccionada:': 'Mesa seleccionada:',
    'Añadir 6 mesas': 'Añadir 6 mesas',
    'No hay mesas configuradas': 'No hay mesas configuradas',
    'personas': 'personas',
    'Disponible': 'Disponible',
    'Ocupada': 'Ocupada',
    'Reservada': 'Reservada',
    'Sucia': 'Sucia',
    'Pedidos en': 'Pedidos en',
    'No hay pedidos en preparación para esta mesa.': 'No hay pedidos en preparación para esta mesa.',
    'Pedido': 'Pedido',
    'Total:': 'Total:',
    'Continuar': 'Continuar',
    'Validar': 'Validar',
    'Cerrar': 'Cerrar',
    'Confirmar Validación': 'Confirmar Validación',
    'Continuando pedido existente': 'Continuando pedido existente',
    'Mesa': 'Mesa',

    // Orders Dashboard
    'Panel de Órdenes': 'Panel de Órdenes',
    'Órdenes Actuales': 'Órdenes Actuales',
    'Historial': 'Historial',
    'En Preparación': 'En Preparación',
    'Completado': 'Completado',
    'Cancelado': 'Cancelado',
    'Desde:': 'Desde:',
    'Hasta:': 'Hasta:',
    'Filtrar': 'Filtrar',
    'Todos los usuarios': 'Todos los usuarios',
    'Mostrar últimas por orden': 'Mostrar últimas por orden',
    'Hoy:': 'Hoy:',
    'Semana:': 'Semana:',
    'Mes:': 'Mes:',
    'Hoy': 'Hoy',
    'Esta Semana': 'Esta Semana',
    'Este Mes': 'Este Mes',
    'Todo': 'Todo',
    'Todos': 'Todos',
    'Aperturas': 'Aperturas',
    'Cierres': 'Cierres',
    'No hay órdenes para mostrar': 'No hay órdenes para mostrar',
    'Empleado:': 'Empleado:',
    'Completar': 'Completar',
    'Eliminar Pedido': 'Eliminar Pedido',
    'No hay historial de órdenes para mostrar': 'No hay historial de órdenes para mostrar',
    'Orden': 'Orden',
    'Fecha': 'Fecha',
    'Estado': 'Estado',
    'Acción': 'Acción',
    'Empleado': 'Empleado',
    'Creada': 'Creada',
    'Actualizada': 'Actualizada',
    'Completada': 'Completada',
    'Cancelada': 'Cancelada',
    'Seleccionar Método de Pago para Completar': 'Seleccionar Método de Pago para Completar',
    'Completar Orden': 'Completar Orden',
    'Confirmar Eliminación': 'Confirmar Eliminación',
    'Esta acción no se puede deshacer. El pedido se moverá a órdenes eliminadas.': 'Esta acción no se puede deshacer. El pedido se moverá a órdenes eliminadas.',
    'Nota de eliminación (obligatoria):': 'Nota de eliminación (obligatoria):',
    'Ingrese la razón de la eliminación...': 'Ingrese la razón de la eliminación...',
    'Eliminando...': 'Eliminando...',
    'Confirmar Eliminación del Pedido': 'Confirmar Eliminación del Pedido',
    'No hay eventos de caja': 'No hay eventos de caja',
    'Apertura': 'Apertura',
    'Cierre': 'Cierre',
    'Monto:': 'Monto:',
    'Nota:': 'Nota:',
    '¿Está seguro de eliminar el pedido': '¿Está seguro de eliminar el pedido',
    'Detalles del pedido:': 'Detalles del pedido:',
    'caracteres': 'caracteres',
    'Seleccionar Método de Pago': 'Seleccionar Método de Pago',
    'Pago en efectivo': 'Pago en efectivo',
    'Pago con tarjeta': 'Pago con tarjeta',
    'Pago digital': 'Pago digital',
    'Error al actualizar el estado': 'Error al actualizar el estado',
    'Orden completada exitosamente': 'Orden completada exitosamente',
    'Error al completar la orden': 'Error al completar la orden',
    'Debe ingresar una nota de eliminación': 'Debe ingresar una nota de eliminación',
    'Pedido eliminado correctamente': 'Pedido eliminado correctamente',
    'Error al completar la orden:': 'Error al completar la orden:',
    'Error al eliminar pedido:': 'Error al eliminar pedido:',

    // Products Manager
    'Gestión de Productos': 'Gestión de Productos',
    'Nuevo Producto': 'Nuevo Producto',
    'Crear': 'Crear',
    'Nombre': 'Nombre',
    'Precio Base': 'Precio Base',
    'Imagen (opcional)': 'Imagen (opcional)',
    'Vista previa': 'Vista previa',
    'Producto': 'Producto',
    'Tamaños': 'Tamaños',
    'Único': 'Único',
    'Sin categoría': 'Sin categoría',
    'Disponible': 'Disponible',
    'No disponible': 'No disponible',
    'Seleccionar categoría': 'Seleccionar categoría',
    'Error al crear producto': 'Error al crear producto',
    'Subiendo imagen...': 'Subiendo imagen...',
    'Error subiendo imagen:': 'Error subiendo imagen:',
    'Verifica el bucket "product-images" y permisos públicos.': 'Verifica el bucket "product-images" y permisos públicos.',
    'Imagen subida correctamente': 'Imagen subida correctamente',
    'No se pudo obtener la URL pública de la imagen.': 'No se pudo obtener la URL pública de la imagen.',
    'Error durante la subida de imagen': 'Error durante la subida de imagen',
    'Producto creado correctamente': 'Producto creado correctamente',
    'Error al actualizar producto': 'Error al actualizar producto',
    'Producto actualizado correctamente': 'Producto actualizado correctamente',
    '¿Estás seguro de que deseas eliminar este producto?': '¿Estás seguro de que deseas eliminar este producto?',
    'El producto será eliminado permanentemente de la lista de productos activos. Los pedidos históricos que contengan este producto se mantendrán intactos.': 'El producto será eliminado permanentemente de la lista de productos activos. Los pedidos históricos que contengan este producto se mantendrán intactos.',
    'Error al verificar el uso del producto': 'Error al verificar el uso del producto',
    'El producto aparece en el historial de pedidos, pero se eliminará correctamente.': 'El producto aparece en el historial de pedidos, pero se eliminará correctamente.',
    'Error al eliminar producto:': 'Error al eliminar producto:',
    'Producto eliminado correctamente. El historial de pedidos se mantiene intacto.': 'Producto eliminado correctamente. El historial de pedidos se mantiene intacto.',
    'Error al eliminar producto': 'Error al eliminar producto',
    'Creando...': 'Creando...',
    'Guardando cambios...': 'Guardando cambios...',
    'Guardar cambios': 'Guardar cambios',
    'Espera a que termine la operación': 'Espera a que termine la operación',
    'Cancelar edición': 'Cancelar edición',
    'Editar producto': 'Editar producto',
    'Eliminar producto permanentemente': 'Eliminar producto permanentemente',

    // Category Manager
    'Gestión de Categorías': 'Gestión de Categorías',
    'Actualizar': 'Actualizar',
    'Actualizar lista': 'Actualizar lista',
    'Editando Categoría': 'Editando Categoría',
    'Nueva Categoría': 'Nueva Categoría',
    'Nombre de la categoría': 'Nombre de la categoría',
    'Editando:': 'Editando:',
    'Guardando...': 'Guardando...',
    'Categorías Existentes': 'Categorías Existentes',
    'Error al cargar categorías:': 'Error al cargar categorías:',
    'Error desconocido': 'Error desconocido',
    'Categoría actualizada correctamente': 'Categoría actualizada correctamente',
    'Categoría creada correctamente': 'Categoría creada correctamente',
    'Error al guardar la categoría:': 'Error al guardar la categoría:',
    '¿Estás seguro de eliminar la categoría': '¿Estás seguro de eliminar la categoría',
    'Esta acción no se puede deshacer.': 'Esta acción no se puede deshacer.',
    'Error al verificar el uso de la categoría': 'Error al verificar el uso de la categoría',
    'No se puede eliminar la categoría porque está siendo usada por': 'No se puede eliminar la categoría porque está siendo usada por',
    'producto(s). Elimine o reasigne los productos primero.': 'producto(s). Elimine o reasigne los productos primero.',
    'Categoría eliminada correctamente': 'Categoría eliminada correctamente',
    'Error al eliminar la categoría:': 'Error al eliminar la categoría:',
    'Cargando categorías...': 'Cargando categorías...',
    'Modificando categoría:': 'Modificando categoría:',
    'Creada:': 'Creada:',
    'No hay categorías creadas': 'No hay categorías creadas',
    'Editar categoría': 'Editar categoría',
    'Eliminar categoría': 'Eliminar categoría',

    // User Manager
    'Gestión de Usuarios': 'Gestión de Usuarios',
    'Nuevo Empleado': 'Nuevo Empleado',
    'Mostrar eliminados': 'Mostrar eliminados',
    'Mostrar inactivos': 'Mostrar inactivos',
    'Nombre Completo': 'Nombre Completo',
    'Correo Electrónico': 'Correo Electrónico',
    'Contraseña': 'Contraseña',
    'Teléfono': 'Teléfono',
    'Rol': 'Rol',
    'Super Administrador': 'Super Administrador',
    'Administrador': 'Administrador',
    'Cajero': 'Cajero',
    'Barista': 'Barista',
    'Camarero': 'Camarero',
    'Crear Empleado': 'Crear Empleado',
    'Empleado': 'Empleado',
    'Contacto': 'Contacto',
    'Correo': 'Correo',
    'Activo': 'Activo',
    'Inactivo': 'Inactivo',
    'Eliminado': 'Eliminado',
    'Solo un Super Administrador puede crear otros Super Administradores': 'Solo un Super Administrador puede crear otros Super Administradores',
    'No se pudo crear el usuario': 'No se pudo crear el usuario',
    'Empleado creado exitosamente. Si la confirmación por email está habilitada, el usuario debe confirmar su correo.': 'Empleado creado exitosamente. Si la confirmación por email está habilitada, el usuario debe confirmar su correo.',
    'Error al crear empleado': 'Error al crear empleado',
    'Usuario': 'Usuario',
    'desactivado': 'desactivado',
    'activado': 'activado',
    'Error al actualizar estado del empleado': 'Error al actualizar estado del empleado',
    'Correo actualizado': 'Correo actualizado',
    'No se pudo actualizar el correo': 'No se pudo actualizar el correo',
    'Este usuario no tiene correo guardado': 'Este usuario no tiene correo guardado',
    'Email de restablecimiento enviado': 'Email de restablecimiento enviado',
    'No se pudo enviar el email de restablecimiento': 'No se pudo enviar el email de restablecimiento',
    'Eliminar lógicamente a': 'Eliminar lógicamente a',
    'Usuario eliminado (borrado lógico)': 'Usuario eliminado (borrado lógico)',
    'No se pudo eliminar el usuario': 'No se pudo eliminar el usuario',
    'Error al cargar empleados': 'Error al cargar empleados',
    'No registrado': 'No registrado',
    'correo@ejemplo.com': 'correo@ejemplo.com',
    'Usuario eliminado': 'Usuario eliminado',
    'Editar correo': 'Editar correo',
    'Guardar correo': 'Guardar correo',
    'Enviar reset de contraseña': 'Enviar reset de contraseña',
    'Sin correo': 'Sin correo',
    'Desactivar': 'Desactivar',
    'Activar': 'Activar',
    'Reset': 'Reset',
    'Guardar': 'Guardar',

    // Login Form
    'La contraseña es obligatoria.': 'La contraseña es obligatoria.',
    'Por favor ingresa un correo electrónico válido.': 'Por favor ingresa un correo electrónico válido.',
    'La contraseña debe tener al menos 6 caracteres.': 'La contraseña debe tener al menos 6 caracteres.',
    'Credenciales inválidas. Por favor intenta de nuevo.': 'Credenciales inválidas. Por favor intenta de nuevo.',
    'Correo electrónico o contraseña incorrectos.': 'Correo electrónico o contraseña incorrectos.',
    'Por favor confirma tu correo electrónico antes de iniciar sesión.': 'Por favor confirma tu correo electrónico antes de iniciar sesión.',
    'Demasiados intentos. Por favor espera unos minutos.': 'Demasiados intentos. Por favor espera unos minutos.',
    'Ocultar contraseña': 'Ocultar contraseña',
    'Mostrar contraseña': 'Mostrar contraseña',
    'empleado@cafeteria.com': 'empleado@cafeteria.com',

    // Analytics - Additional texts
    'Activos': 'Activos',
    'Usuarios conectados': 'Usuarios conectados',
    'Ahora': 'Ahora',
    'Hora actual': 'Hora actual',
    'Generar Reporte Diario': 'Generar Reporte Diario',
    'Generar Reporte Semanal': 'Generar Reporte Semanal',
    'Generar Reporte Mensual': 'Generar Reporte Mensual',
    'sesiones': 'sesiones',
    'pedidos': 'pedidos',
    'Motivo:': 'Motivo:',
    'órdenes': 'órdenes',
    'unidades': 'unidades',
    'Margen bajo hoy:': 'Margen bajo hoy:',
    'Considera revisar precios o reducir gastos.': 'Considera revisar precios o reducir gastos.',
    'Pérdidas esta semana.': 'Pérdidas esta semana.',
    'Los gastos superan las ventas. Revisa el control de inventario y gastos operativos.': 'Los gastos superan las ventas. Revisa el control de inventario y gastos operativos.',
    'Empleados inactivos.': 'Empleados inactivos.',
    'Algunos empleados conectados no han procesado pedidos hoy.': 'Algunos empleados conectados no han procesado pedidos hoy.',
    'Ningún empleado conectado.': 'Ningún empleado conectado.',
    'Verifica la conectividad y horarios de trabajo.': 'Verifica la conectividad y horarios de trabajo.',

    // Company Settings - Additional texts (many already exist in lines 63-80)
    'Error al cargar configuración de la empresa': 'Error al cargar configuración de la empresa',
    'Configuración por defecto creada': 'Configuración por defecto creada',
    'Error al crear configuración por defecto': 'Error al crear configuración por defecto',
    'Restaurando permisos...': 'Restaurando permisos...',
    'Todos los permisos restaurados para super_admin': 'Todos los permisos restaurados para super_admin',
    'Error al restaurar permisos': 'Error al restaurar permisos',
    'Impresoras de tickets actualizadas': 'Impresoras de tickets actualizadas',
    'Error consultando la base de datos': 'Error consultando la base de datos',
    'Revisa la consola para el contenido de la base de datos': 'Revisa la consola para el contenido de la base de datos',
    'Error verificando la base de datos': 'Error verificando la base de datos',
    'El nombre de la empresa es obligatorio': 'El nombre de la empresa es obligatorio',
    'Error al guardar la configuración:': 'Error al guardar la configuración:',
    'Cargando configuración...': 'Cargando configuración...',
    'Guardando...': 'Guardando...',
    '¿Problemas con permisos?': '¿Problemas con permisos?',
    'Si no puedes acceder a esta página o a la gestión de roles, usa el botón de emergencia para restaurar todos los permisos del super_admin.': 'Si no puedes acceder a esta página o a la gestión de roles, usa el botón de emergencia para restaurar todos los permisos del super_admin.',
    'Restaurar Todos los Permisos (Super Admin)': 'Restaurar Todos los Permisos (Super Admin)',
    'Información de Depuración:': 'Información de Depuración:',
    'Nombre Actual de Empresa:': 'Nombre Actual de Empresa:',
    'Dirección Actual:': 'Dirección Actual:',
    'Teléfono Actual:': 'Teléfono Actual:',
    'ID de Configuración:': 'ID de Configuración:',
    'Sin ID (nuevo registro)': 'Sin ID (nuevo registro)',
    'Tiene Cambios:': 'Tiene Cambios:',
    'Sí': 'Sí',
    'No': 'No',
    'Verificar Base de Datos': 'Verificar Base de Datos',
    'Forzar Actualización de Tickets': 'Forzar Actualización de Tickets',
    'Restaurar Permisos': 'Restaurar Permisos',
    'Usa estos botones para depurar el problema. Revisa la consola del navegador para logs detallados.': 'Usa estos botones para depurar el problema. Revisa la consola del navegador para logs detallados.',
    'Nombre de empresa': 'Nombre de empresa',
    'No establecido': 'No establecido',

    // Cash Register Dashboard
    'Error al cargar sesiones de caja': 'Error al cargar sesiones de caja',
    'Gestión de Caja': 'Gestión de Caja',
    'Historial de aperturas y cierres de caja': 'Historial de aperturas y cierres de caja',
    'Total Aperturas': 'Total Aperturas',
    'Total Cierres': 'Total Cierres',
    'Estado Actual': 'Estado Actual',
    'Caja Abierta': 'Caja Abierta',
    'Caja Cerrada': 'Caja Cerrada',
    'Fecha Inicio': 'Fecha Inicio',
    'Fecha Fin': 'Fecha Fin',
    'Abiertas': 'Abiertas',
    'Cerradas': 'Cerradas',
    'Todos los empleados': 'Todos los empleados',
    'Sesiones de Hoy': 'Sesiones de Hoy',
    'Mostrando todas tus sesiones de caja del día actual': 'Mostrando todas tus sesiones de caja del día actual',
    'Cargando sesiones...': 'Cargando sesiones...',
    'No hay sesiones de caja para mostrar': 'No hay sesiones de caja para mostrar',
    'Primera Apertura': 'Primera Apertura',
    'Último Cierre': 'Último Cierre',
    'Total Inicial': 'Total Inicial',
    'Total Final': 'Total Final',
    'Sesiones': 'Sesiones',
    'Acciones': 'Acciones',
    'Imprimir reporte diario': 'Imprimir reporte diario',
    'Error al generar el reporte diario': 'Error al generar el reporte diario',
    'Error al generar el reporte': 'Error al generar el reporte',
    'Reporte Diario de Caja': 'Reporte Diario de Caja',
    'Sesiones de Caja': 'Sesiones de Caja',
    'Hora Apertura': 'Hora Apertura',
    'Hora Cierre': 'Hora Cierre',
    'Firma del Empleado': 'Firma del Empleado',
    'Reporte de Caja': 'Reporte de Caja',
    'Tú': 'Tú',
    'Abierta': 'Abierta',
    'Cerrada': 'Cerrada',
    'Monto Apertura': 'Monto Apertura',
    'Monto Cierre': 'Monto Cierre',
    'Órdenes del día': 'Órdenes del día',
    'Cantidad': 'Cantidad',
    'Este documento es oficial y forma parte del registro contable de': 'Este documento es oficial y forma parte del registro contable de',

    // Cash Register - New logic translations
    'Apertura': 'Apertura',
    'Ventas': 'Ventas',
    'Retiros': 'Retiros',
    'Cierre Esperado': 'Cierre Esperado',
    'Cierre Real': 'Cierre Real',
    'Diferencia': 'Diferencia',
    'Retiro': 'Retiro',
    'Registrar Retiro de Caja': 'Registrar Retiro de Caja',
    'Monto a retirar': 'Monto a retirar',
    'Motivo del retiro': 'Motivo del retiro',
    'Seleccionar motivo': 'Seleccionar motivo',
    'Depósito bancario': 'Depósito bancario',
    'Pago a proveedor': 'Pago a proveedor',
    'Gastos operativos': 'Gastos operativos',
    'Cambio de billetes': 'Cambio de billetes',
    'Otros': 'Otros',
    'Notas adicionales': 'Notas adicionales',
    'opcional': 'opcional',
    'Detalles adicionales sobre el retiro...': 'Detalles adicionales sobre el retiro...',
    'Importante': 'Importante',
    'Este retiro se restará del cálculo del cierre de caja esperado.': 'Este retiro se restará del cálculo del cierre de caja esperado.',
    'Registrar retiro de caja': 'Registrar retiro de caja',
    'Por favor completa todos los campos obligatorios': 'Por favor completa todos los campos obligatorios',
    'Retiro registrado exitosamente': 'Retiro registrado exitosamente',
    'Error al registrar el retiro': 'Error al registrar el retiro',
    'Registrar Retiro': 'Registrar Retiro',

    // Cash Closing Modal
    'Revise el resumen y confirme el cierre': 'Revise el resumen y confirme el cierre',
    'Resumen del Día': 'Resumen del Día',
    'Monto Real en Caja': 'Monto Real en Caja',
    'Hay más dinero del esperado': 'Hay más dinero del esperado',
    'Hay menos dinero del esperado': 'Hay menos dinero del esperado',
    'Error al cargar información de caja': 'Error al cargar información de caja',
    'Ingrese un monto de cierre válido (>= 0)': 'Ingrese un monto de cierre válido (>= 0)',
    'RESUMEN FINANCIERO': 'RESUMEN FINANCIERO',
    'RETIROS DE CAJA': 'RETIROS DE CAJA',
    'Sin pedidos': 'Sin pedidos',
    'Motivo': 'Motivo',
    'Nota': 'Nota',

    // Cash Opening Modal
    'Apertura de Caja': 'Apertura de Caja',
    'Bienvenido! Ingrese el monto inicial en caja': 'Bienvenido! Ingrese el monto inicial en caja',
    'Este monto será el punto de partida para el control de caja del día.': 'Este monto será el punto de partida para el control de caja del día.',
    'Monto de Apertura': 'Monto de Apertura',
    'Monto inicial en caja': 'Monto inicial en caja',
    'Abriendo...': 'Abriendo...',
    'Abrir Caja': 'Abrir Caja',
    'Ingrese un monto de apertura válido (>= 0)': 'Ingrese un monto de apertura válido (>= 0)',
    'Caja abierta exitosamente': 'Caja abierta exitosamente',
    'No se pudo abrir la caja:': 'No se pudo abrir la caja:',

    // Expense Manager
    'Salarios': 'Salarios',
    'Alquiler': 'Alquiler',
    'Servicios': 'Servicios',
    'Mantenimiento': 'Mantenimiento',
    'Otras categorías': 'Otras categorías',
    'Error al cargar proveedores': 'Error al cargar proveedores',
    'Error al cargar gastos': 'Error al cargar gastos',
    'Gasto registrado exitosamente': 'Gasto registrado exitosamente',
    'Error al registrar gasto': 'Error al registrar gasto',
    'Gestión de Gastos': 'Gestión de Gastos',
    'Descargar Reporte': 'Descargar Reporte',
    'Nuevo Gasto': 'Nuevo Gasto',
    'Categoría / Proveedor': 'Categoría / Proveedor',
    'Seleccionar categoría o proveedor': 'Seleccionar categoría o proveedor',
    'Descripción': 'Descripción',
    'Guardar Gasto': 'Guardar Gasto',
    'Todas las categorías': 'Todas las categorías',
    'Fecha Inicial': 'Fecha Inicial',
    'Fecha Final': 'Fecha Final',
    'Lista de Gastos': 'Lista de Gastos',
    'No hay gastos registrados en este período': 'No hay gastos registrados en este período',

    // Supplier Manager
    'Proveedor actualizado': 'Proveedor actualizado',
    'Proveedor creado': 'Proveedor creado',
    'Error al guardar proveedor': 'Error al guardar proveedor',
    'Proveedor eliminado': 'Proveedor eliminado',
    'Error al eliminar proveedor': 'Error al eliminar proveedor',
    'Gestión de Proveedores': 'Gestión de Proveedores',
    'Nuevo Proveedor': 'Nuevo Proveedor',
    'Editar Proveedor': 'Editar Proveedor',
    'Persona de Contacto': 'Persona de Contacto',
    'Email/Teléfono': 'Email/Teléfono',
    'No hay proveedores registrados': 'No hay proveedores registrados',
    'Contacto': 'Contacto',

    // Employee Time Tracking
    'Error al cargar empleados': 'Error al cargar empleados',
    'Error al cargar estadísticas': 'Error al cargar estadísticas',
    'No hay datos para exportar': 'No hay datos para exportar',
    'Reporte generado exitosamente': 'Reporte generado exitosamente',
    'Error al generar reporte': 'Error al generar reporte',
    'Gestión de Tiempo de Empleados': 'Gestión de Tiempo de Empleados',
    'Seleccionar Empleado': 'Seleccionar Empleado',
    'Seleccione un empleado': 'Seleccione un empleado',
    'Horas trabajadas': 'Horas trabajadas',
    'Horas por día': 'Horas por día',
    'Días trabajados': 'Días trabajados',
    'Ventas totales': 'Ventas totales',
    'Órdenes procesadas': 'Órdenes procesadas',
    'Entrada': 'Entrada',
    'Salida': 'Salida',
    'En curso': 'En curso',
    'Exportar Resumen': 'Exportar Resumen',
    'Exportar Detalle Diario': 'Exportar Detalle Diario',
    'Exportar Sesiones': 'Exportar Sesiones',
    'No especificada': 'No especificada',
    'No especificado': 'No especificado',
    'No configurada': 'No configurada',

    // Role Management
    'Gestión de Roles y Permisos': 'Gestión de Roles y Permisos',
    'Configure los accesos para cada rol del sistema': 'Configure los accesos para cada rol del sistema',
    'Cargando permisos...': 'Cargando permisos...',
    'Error al cargar permisos': 'Error al cargar permisos',
    'Permisos actualizados correctamente': 'Permisos actualizados correctamente',
    'Error al guardar permisos': 'Error al guardar permisos',
    'Ventas': 'Ventas',
    'Inventario': 'Inventario',
    'Finanzas': 'Finanzas',
    'Sistema': 'Sistema',
    'Órdenes': 'Órdenes',
    'Usuarios': 'Usuarios',
    'Caja': 'Caja',
    'Tiempo Empleados': 'Tiempo Empleados',
    'Proveedores': 'Proveedores',
    'Gastos': 'Gastos',
    'Analíticas': 'Analíticas',
    'Productos': 'Productos',
    'Categorías': 'Categorías',
    'Gestión de Roles': 'Gestión de Roles',
    'habilitadas': 'habilitadas',
    'Acceso completo': 'Acceso completo',
    'Acceso parcial': 'Acceso parcial',
    'Sin acceso': 'Sin acceso',
    'Permisos específicos:': 'Permisos específicos:',
    'Confirmar pedidos': 'Confirmar pedidos',
    'Validar pedidos (finalizar con pago)': 'Validar pedidos (finalizar con pago)',
    'Información sobre roles:': 'Información sobre roles:',
    'Acceso completo incluyendo gestión de roles': 'Acceso completo incluyendo gestión de roles',
    'Acceso completo excepto gestión de roles': 'Acceso completo excepto gestión de roles',
    'Ventas y gestión de caja': 'Ventas y gestión de caja',
    'Solo sección de ventas': 'Solo sección de ventas',
    'Sala y órdenes (sin validar pedidos)': 'Sala y órdenes (sin validar pedidos)',

    // App Settings
    'Configuración de la aplicación': 'Configuración de la aplicación',
    'Personaliza el idioma y la apariencia de la aplicación. Los cambios se aplican inmediatamente.': 'Personaliza el idioma y la apariencia de la aplicación. Los cambios se aplican inmediatamente.',
    'Español': 'Español',
    'Français': 'Français',
    'Selecciona el tema de color de la aplicación': 'Selecciona el tema de color de la aplicación',
    'Tema claro': 'Tema claro',
    'Tema oscuro': 'Tema oscuro',
    'Automático': 'Automático',
    'Información': 'Información',
    'Los cambios de idioma se aplican inmediatamente a toda la aplicación': 'Los cambios de idioma se aplican inmediatamente a toda la aplicación',
    'La configuración se guarda automáticamente en tu navegador': 'La configuración se guarda automáticamente en tu navegador',
    'Puedes cambiar entre idiomas en cualquier momento': 'Puedes cambiar entre idiomas en cualquier momento',
    'El tema automático sigue la configuración de tu sistema operativo': 'El tema automático sigue la configuración de tu sistema operativo',

    // Navigation & Cash Register
    'Ingrese un monto de cierre válido (>= 0)': 'Ingrese un monto de cierre válido (>= 0)',
    'No hay sesión de caja abierta para cerrar. Se cerrará la sesión de usuario.': 'No hay sesión de caja abierta para cerrar. Se cerrará la sesión de usuario.',
    'Cierre de caja registrado e impreso.': 'Cierre de caja registrado e impreso.',
    'No se pudo cerrar la caja:': 'No se pudo cerrar la caja:',
    '¿Desea cerrar la sesión de caja antes de salir?': '¿Desea cerrar la sesión de caja antes de salir?',
    'Monto de cierre': 'Monto de cierre',
    'Salir Sin Cambios': 'Salir Sin Cambios',
    'Cerrar Caja y Salir': 'Cerrar Caja y Salir',
    'CIERRE DE CAJA': 'CIERRE DE CAJA',
    'Empleado:': 'Empleado:',
    'SESIONES DEL DÍA': 'SESIONES DEL DÍA',
    'Sesión': 'Sesión',
    'RESUMEN FINANCIERO': 'RESUMEN FINANCIERO',
    'Primera Apertura:': 'Primera Apertura:',
    'Cierre Final:': 'Cierre Final:',
    'Resultado del Día:': 'Resultado del Día:',
    'Total Pedidos:': 'Total Pedidos:',
    'Total Ventas:': 'Total Ventas:',
    'PEDIDOS DEL DÍA': 'PEDIDOS DEL DÍA',
    'Pedido #': 'Pedido #',
    'Hora:': 'Hora:',
    'Producto': 'Producto',
    'Generado el': 'Generado el',
    'El cambio de idioma se aplicará a todos los usuarios del sistema de forma inmediata.': 'El cambio de idioma se aplicará a todos los usuarios del sistema de forma inmediata.',
  },
  fr: {
    // Navigation
    'nav.sales': 'Ventes',
    'nav.inventory': 'Inventaire',
    'nav.finance': 'Finances',
    'nav.system': 'Système',
    'nav.floor': 'Salle',
    'nav.pos': 'Point de Vente',
    'nav.orders': 'Commandes',
    'nav.products': 'Produits',
    'nav.categories': 'Catégories',
    'nav.users': 'Utilisateurs',
    'nav.cash': 'Caisse',
    'nav.time-tracking': 'Temps Employés',
    'nav.suppliers': 'Fournisseurs',
    'nav.expenses': 'Dépenses',
    'nav.analytics': 'Analytiques',
    'nav.role-management': 'Gestion des Rôles',
    'nav.company-settings': 'Informations Entreprise',
    'nav.app-settings': 'Configuration',

    // Actions communes
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',

    // Configuration
    'settings.language': 'Langue',
    'settings.language.es': 'Espagnol',
    'settings.language.fr': 'Français',
    'settings.language.description': 'Sélectionnez la langue de l\'application',
    'settings.general': 'Configuration Générale',
    'settings.general.description': 'Personnalisez le comportement de l\'application',
    'settings.theme': 'Thème',
    'settings.theme.light': 'Clair',
    'settings.theme.dark': 'Sombre',
    'settings.theme.auto': 'Automatique',

    // Messages
    'messages.language-changed': 'Langue changée avec succès',
    'messages.settings-saved': 'Configuration sauvegardée avec succès',

    // État de connexion
    'Available': 'Disponible',
    'Not available': 'Non disponible',
    'Status changed to: Available': 'Statut changé en : Disponible',
    'Status changed to: Not available': 'Statut changé en : Non disponible',
    'Click to mark yourself as unavailable': 'Cliquez pour vous marquer comme non disponible',
    'Click to mark yourself as available': 'Cliquez pour vous marquer comme disponible',
    'connected': 's\'est connecté(e)',
    'disconnected': 's\'est déconnecté(e)',

    // Notifications
    'cerró caja': 'a fermé la caisse',
    'abrió caja': 'a ouvert la caisse',
    'Pedido': 'Commande',
    'eliminado por': 'supprimée par',
    'completado por': 'complétée par',

    // Configuration entreprise
    'Información de la Empresa': 'Informations de l\'Entreprise',
    'Configure los datos que aparecen en tickets y reportes': 'Configurez les données qui apparaissent sur les tickets et rapports',
    'Esta información aparecerá en:': 'Ces informations apparaîtront dans :',
    'Todos los tickets de venta impresos': 'Tous les tickets de vente imprimés',
    'Reportes Excel exportados desde Analíticas': 'Rapports Excel exportés depuis Analytics',
    'Reportes de tiempo de empleados': 'Rapports de temps des employés',
    'Cualquier documento generado por el sistema': 'Tout document généré par le système',
    'Nombre de la Empresa': 'Nom de l\'Entreprise',
    'Dirección': 'Adresse',
    'Número de Teléfono': 'Numéro de Téléphone',
    'Guardar Cambios': 'Enregistrer les Modifications',
    'Deshacer': 'Annuler',
    'Vista Previa (Tickets)': 'Aperçu (Tickets)',
    'Información de pedido...': 'Informations de commande...',
    'Este nombre aparecerá en todos los documentos': 'Ce nom apparaîtra sur tous les documents',
    'Dirección física de la empresa': 'Adresse physique de l\'entreprise',
    'Número de contacto para clientes': 'Numéro de contact pour les clients',

    // Système de Gestion
    'Sistema de Gestión': 'Système de Gestion',
    'Menú de Navegación': 'Menu de Navigation',
    'Menú Admin': 'Menu Admin',
    'Salir': 'Quitter',
    'Cerrar Sesión': 'Fermer la Session',
    'Sala': 'Salle',
    'Pedidos': 'Commandes',
    'Punto de Venta': 'Point de Vente',
    'Apertura de Caja': 'Ouverture de Caisse',
    'Indique el monto inicial en caja para comenzar su turno.': 'Indiquez le montant initial en caisse pour commencer votre service.',
    'Cierre de Caja': 'Fermeture de Caisse',
    'Indique el monto final en caja antes de cerrar sesión.': 'Indiquez le montant final en caisse avant de fermer la session.',

    // POS - Punto de Venta
    'Cargando productos...': 'Chargement des produits...',
    'Reintentar': 'Réessayer',
    'Todos': 'Tous',
    'Agregar': 'Ajouter',
    'Agregar al carrito': 'Ajouter au panier',
    'Cargar más productos': 'Charger plus de produits',
    'Carrito de Compras': 'Panier d\'Achats',
    'El carrito está vacío': 'Le panier est vide',
    'Selecciona productos para comenzar': 'Sélectionnez des produits pour commencer',
    'Para llevar': 'À emporter',
    'En sala': 'En salle',
    'Seleccione mesa': 'Sélectionnez une table',
    'Confirmar Pedido': 'Confirmer la Commande',
    'Seleccionar Método de Pago': 'Sélectionner le Mode de Paiement',
    'Efectivo': 'Espèces',
    'Pago en efectivo': 'Paiement en espèces',
    'Tarjeta': 'Carte',
    'Pago con tarjeta': 'Paiement par carte',
    'Digital': 'Numérique',
    'Pago digital': 'Paiement numérique',
    'Cancelar': 'Annuler',
    'Total del Pedido:': 'Total de la Commande :',
    'Método de Pago:': 'Mode de Paiement :',
    'Después': 'Après',
    'Validar e Imprimir': 'Valider et Imprimer',

    // Login Form
    'Correo Electrónico': 'Adresse e-mail',
    'Contraseña': 'Mot de passe',
    'Iniciando sesión...': 'Connexion en cours...',
    'Iniciar Sesión': 'Se connecter',
    'El correo electrónico es obligatorio.': 'L\'adresse e-mail est obligatoire.',
    'La contraseña es obligatoria.': 'Le mot de passe est obligatoire.',
    'Por favor ingresa un correo electrónico válido.': 'Veuillez saisir une adresse e-mail valide.',
    'La contraseña debe tener al menos 6 caracteres.': 'Le mot de passe doit contenir au moins 6 caractères.',
    'Credenciales inválidas. Por favor intenta de nuevo.': 'Identifiants invalides. Veuillez réessayer.',
    'Correo electrónico o contraseña incorrectos.': 'Adresse e-mail ou mot de passe incorrect.',
    'Por favor confirma tu correo electrónico antes de iniciar sesión.': 'Veuillez confirmer votre adresse e-mail avant de vous connecter.',
    'Demasiados intentos. Por favor espera unos minutos.': 'Trop de tentatives. Veuillez attendre quelques minutes.',
    'Ocultar contraseña': 'Masquer le mot de passe',
    'Mostrar contraseña': 'Afficher le mot de passe',
    'empleado@cafeteria.com': 'employe@cafeteria.com',

    // Analytics - Additional texts
    'Activos': 'Actifs',
    'Usuarios conectados': 'Utilisateurs connectés',
    'Ahora': 'Maintenant',
    'Hora actual': 'Heure actuelle',
    'Generar Reporte Diario': 'Générer un Rapport Quotidien',
    'Generar Reporte Semanal': 'Générer un Rapport Hebdomadaire',
    'Generar Reporte Mensual': 'Générer un Rapport Mensuel',
    'sesiones': 'sessions',
    'pedidos': 'commandes',
    'Motivo:': 'Motif :',
    'órdenes': 'commandes',
    'unidades': 'unités',
    'Margen bajo hoy:': 'Marge faible aujourd\'hui :',
    'Considera revisar precios o reducir gastos.': 'Envisagez de réviser les prix ou de réduire les dépenses.',
    'Pérdidas esta semana.': 'Pertes cette semaine.',
    'Los gastos superan las ventas. Revisa el control de inventario y gastos operativos.': 'Les dépenses dépassent les ventes. Vérifiez le contrôle des stocks et les dépenses opérationnelles.',
    'Empleados inactivos.': 'Employés inactifs.',
    'Algunos empleados conectados no han procesado pedidos hoy.': 'Certains employés connectés n\'ont pas traité de commandes aujourd\'hui.',
    'Ningún empleado conectado.': 'Aucun employé connecté.',
    'Verifica la conectividad y horarios de trabajo.': 'Vérifiez la connectivité et les horaires de travail.',

    // Company Settings - Additional texts (many already exist in lines 457-474)
    'Error al cargar configuración de la empresa': 'Erreur lors du chargement de la configuration de l\'entreprise',
    'Configuración por defecto creada': 'Configuration par défaut créée',
    'Error al crear configuración por defecto': 'Erreur lors de la création de la configuration par défaut',
    'Restaurando permisos...': 'Restauration des permissions...',
    'Todos los permisos restaurados para super_admin': 'Toutes les permissions restaurées pour super_admin',
    'Error al restaurar permisos': 'Erreur lors de la restauration des permissions',
    'Impresoras de tickets actualizadas': 'Imprimantes de tickets mises à jour',
    'Error consultando la base de datos': 'Erreur lors de la consultation de la base de données',
    'Revisa la consola para el contenido de la base de datos': 'Consultez la console pour le contenu de la base de données',
    'Error verificando la base de datos': 'Erreur lors de la vérification de la base de données',
    'El nombre de la empresa es obligatorio': 'Le nom de l\'entreprise est obligatoire',
    'Error al guardar la configuración:': 'Erreur lors de l\'enregistrement de la configuration :',
    'Cargando configuración...': 'Chargement de la configuration...',
    'Guardando...': 'Enregistrement...',
    '¿Problemas con permisos?': 'Problèmes avec les permissions ?',
    'Si no puedes acceder a esta página o a la gestión de roles, usa el botón de emergencia para restaurar todos los permisos del super_admin.': 'Si vous ne pouvez pas accéder à cette page ou à la gestion des rôles, utilisez le bouton d\'urgence pour restaurer toutes les permissions du super_admin.',
    'Restaurar Todos los Permisos (Super Admin)': 'Restaurer Toutes les Permissions (Super Admin)',
    'Información de Depuración:': 'Informations de Débogage :',
    'Nombre Actual de Empresa:': 'Nom Actuel de l\'Entreprise :',
    'Dirección Actual:': 'Adresse Actuelle :',
    'Teléfono Actual:': 'Téléphone Actuel :',
    'ID de Configuración:': 'ID de Configuration :',
    'Sin ID (nuevo registro)': 'Sans ID (nouvel enregistrement)',
    'Tiene Cambios:': 'A des Changements :',
    'Sí': 'Oui',
    'No': 'Non',
    'Verificar Base de Datos': 'Vérifier la Base de Données',
    'Forzar Actualización de Tickets': 'Forcer la Mise à Jour des Tickets',
    'Restaurar Permisos': 'Restaurer les Permissions',
    'Usa estos botones para depurar el problema. Revisa la consola del navegador para logs detallados.': 'Utilisez ces boutons pour déboguer le problème. Consultez la console du navigateur pour des logs détaillés.',
    'Nombre de empresa': 'Nom d\'entreprise',
    'No establecido': 'Non défini',

    // Cash Register Dashboard
    'Error al cargar sesiones de caja': 'Erreur lors du chargement des sessions de caisse',
    'Gestión de Caja': 'Gestion de Caisse',
    'Historial de aperturas y cierres de caja': 'Historique des ouvertures et fermetures de caisse',
    'Total Aperturas': 'Total Ouvertures',
    'Total Cierres': 'Total Fermetures',
    'Estado Actual': 'État Actuel',
    'Caja Abierta': 'Caisse Ouverte',
    'Caja Cerrada': 'Caisse Fermée',
    'Fecha Inicio': 'Date Début',
    'Fecha Fin': 'Date Fin',
    'Abiertas': 'Ouvertes',
    'Cerradas': 'Fermées',
    'Todos los empleados': 'Tous les employés',
    'Sesiones de Hoy': 'Sessions d\'Aujourd\'hui',
    'Mostrando todas tus sesiones de caja del día actual': 'Affichage de toutes vos sessions de caisse du jour actuel',
    'Cargando sesiones...': 'Chargement des sessions...',
    'No hay sesiones de caja para mostrar': 'Aucune session de caisse à afficher',
    'Primera Apertura': 'Première Ouverture',
    'Último Cierre': 'Dernière Fermeture',
    'Total Inicial': 'Total Initial',
    'Total Final': 'Total Final',
    'Sesiones': 'Sessions',
    'Acciones': 'Actions',
    'Imprimir reporte diario': 'Imprimer le rapport quotidien',
    'Error al generar el reporte diario': 'Erreur lors de la génération du rapport quotidien',
    'Error al generar el reporte': 'Erreur lors de la génération du rapport',
    'Reporte Diario de Caja': 'Rapport Quotidien de Caisse',
    'Sesiones de Caja': 'Sessions de Caisse',
    'Hora Apertura': 'Heure Ouverture',
    'Hora Cierre': 'Heure Fermeture',
    'Firma del Empleado': 'Signature de l\'Employé',
    'Reporte de Caja': 'Rapport de Caisse',
    'Tú': 'Vous',
    'Abierta': 'Ouverte',
    'Cerrada': 'Fermée',
    'Monto Apertura': 'Montant Ouverture',
    'Monto Cierre': 'Montant Fermeture',
    'Órdenes del día': 'Commandes du jour',
    'Cantidad': 'Quantité',
    'Este documento es oficial y forma parte del registro contable de': 'Ce document est officiel et fait partie de l\'enregistrement comptable de',

    // Cash Register - New logic translations
    'Apertura': 'Ouverture',
    'Ventas': 'Ventes',
    'Retiros': 'Retraits',
    'Cierre Esperado': 'Fermeture Prévue',
    'Cierre Real': 'Fermeture Réelle',
    'Diferencia': 'Différence',
    'Retiro': 'Retrait',
    'Registrar Retiro de Caja': 'Enregistrer un Retrait de Caisse',
    'Monto a retirar': 'Montant à retirer',
    'Motivo del retiro': 'Raison du retrait',
    'Seleccionar motivo': 'Sélectionner une raison',
    'Depósito bancario': 'Dépôt bancaire',
    'Pago a proveedor': 'Paiement au fournisseur',
    'Gastos operativos': 'Dépenses opérationnelles',
    'Cambio de billetes': 'Change de billets',
    'Otros': 'Autres',
    'Notas adicionales': 'Notes additionnelles',
    'opcional': 'optionnel',
    'Detalles adicionales sobre el retiro...': 'Détails supplémentaires sur le retrait...',
    'Importante': 'Important',
    'Este retiro se restará del cálculo del cierre de caja esperado.': 'Ce retrait sera soustrait du calcul de la fermeture de caisse prévue.',
    'Registrar retiro de caja': 'Enregistrer un retrait de caisse',
    'Por favor completa todos los campos obligatorios': 'Veuillez remplir tous les champs obligatoires',
    'Retiro registrado exitosamente': 'Retrait enregistré avec succès',
    'Error al registrar el retiro': 'Erreur lors de l\'enregistrement du retrait',
    'Registrar Retiro': 'Enregistrer le Retrait',

    // Cash Closing Modal
    'Revise el resumen y confirme el cierre': 'Vérifiez le résumé et confirmez la fermeture',
    'Resumen del Día': 'Résumé du Jour',
    'Monto Real en Caja': 'Montant Réel en Caisse',
    'Hay más dinero del esperado': 'Il y a plus d\'argent que prévu',
    'Hay menos dinero del esperado': 'Il y a moins d\'argent que prévu',
    'Error al cargar información de caja': 'Erreur lors du chargement des informations de caisse',
    'Ingrese un monto de cierre válido (>= 0)': 'Veuillez entrer un montant de fermeture valide (>= 0)',
    'RESUMEN FINANCIERO': 'RÉSUMÉ FINANCIER',
    'RETIROS DE CAJA': 'RETRAITS DE CAISSE',
    'Sin pedidos': 'Sans commandes',
    'Motivo': 'Raison',
    'Nota': 'Note',

    // Cash Opening Modal
    'Apertura de Caja': 'Ouverture de Caisse',
    'Bienvenido! Ingrese el monto inicial en caja': 'Bienvenue! Entrez le montant initial en caisse',
    'Este monto será el punto de partida para el control de caja del día.': 'Ce montant sera le point de départ pour le contrôle de caisse du jour.',
    'Monto de Apertura': 'Montant d\'Ouverture',
    'Monto inicial en caja': 'Montant initial en caisse',
    'Abriendo...': 'Ouverture...',
    'Abrir Caja': 'Ouvrir la Caisse',
    'Ingrese un monto de apertura válido (>= 0)': 'Veuillez entrer un montant d\'ouverture valide (>= 0)',
    'Caja abierta exitosamente': 'Caisse ouverte avec succès',
    'No se pudo abrir la caja:': 'Impossible d\'ouvrir la caisse:',

    // Expense Manager
    'Salarios': 'Salaires',
    'Alquiler': 'Loyer',
    'Servicios': 'Services',
    'Mantenimiento': 'Entretien',
    'Otras categorías': 'Autres catégories',
    'Error al cargar proveedores': 'Erreur lors du chargement des fournisseurs',
    'Error al cargar gastos': 'Erreur lors du chargement des dépenses',
    'Gasto registrado exitosamente': 'Dépense enregistrée avec succès',
    'Error al registrar gasto': 'Erreur lors de l\'enregistrement de la dépense',
    'Gestión de Gastos': 'Gestion des Dépenses',
    'Descargar Reporte': 'Télécharger le Rapport',
    'Nuevo Gasto': 'Nouvelle Dépense',
    'Categoría / Proveedor': 'Catégorie / Fournisseur',
    'Seleccionar categoría o proveedor': 'Sélectionner catégorie ou fournisseur',
    'Descripción': 'Description',
    'Guardar Gasto': 'Enregistrer la Dépense',
    'Todas las categorías': 'Toutes les catégories',
    'Fecha Inicial': 'Date Initiale',
    'Fecha Final': 'Date Finale',
    'Lista de Gastos': 'Liste des Dépenses',
    'No hay gastos registrados en este período': 'Aucune dépense enregistrée pour cette période',

    // Supplier Manager
    'Proveedor actualizado': 'Fournisseur mis à jour',
    'Proveedor creado': 'Fournisseur créé',
    'Error al guardar proveedor': 'Erreur lors de l\'enregistrement du fournisseur',
    'Proveedor eliminado': 'Fournisseur supprimé',
    'Error al eliminar proveedor': 'Erreur lors de la suppression du fournisseur',
    'Gestión de Proveedores': 'Gestion des Fournisseurs',
    'Nuevo Proveedor': 'Nouveau Fournisseur',
    'Editar Proveedor': 'Modifier le Fournisseur',
    'Persona de Contacto': 'Personne de Contact',
    'Email/Teléfono': 'Email/Téléphone',
    'No hay proveedores registrados': 'Aucun fournisseur enregistré',
    'Contacto': 'Contact',

    // Employee Time Tracking
    'Error al cargar empleados': 'Erreur lors du chargement des employés',
    'Error al cargar estadísticas': 'Erreur lors du chargement des statistiques',
    'No hay datos para exportar': 'Aucune donnée à exporter',
    'Reporte generado exitosamente': 'Rapport généré avec succès',
    'Error al generar reporte': 'Erreur lors de la génération du rapport',
    'Gestión de Tiempo de Empleados': 'Gestion du Temps des Employés',
    'Seleccionar Empleado': 'Sélectionner un Employé',
    'Seleccione un empleado': 'Sélectionnez un employé',
    'Horas trabajadas': 'Heures travaillées',
    'Horas por día': 'Heures par jour',
    'Días trabajados': 'Jours travaillés',
    'Ventas totales': 'Ventes totales',
    'Órdenes procesadas': 'Commandes traitées',
    'Entrada': 'Entrée',
    'Salida': 'Sortie',
    'En curso': 'En cours',
    'Exportar Resumen': 'Exporter le Résumé',
    'Exportar Detalle Diario': 'Exporter le Détail Quotidien',
    'Exportar Sesiones': 'Exporter les Sessions',
    'No especificada': 'Non spécifiée',
    'No especificado': 'Non spécifié',
    'No configurada': 'Non configurée',

    // Role Management
    'Gestión de Roles y Permisos': 'Gestion des Rôles et Permissions',
    'Configure los accesos para cada rol del sistema': 'Configurez les accès pour chaque rôle du système',
    'Cargando permisos...': 'Chargement des permissions...',

    // Analytics
    'Analíticas y Reportes': 'Analyses et Rapports',
    'usuarios conectados': 'utilisateurs connectés',
    'mesas ocupadas': 'tables occupées',
    'Exportar Excel': 'Exporter Excel',
    'Ventas del día': 'Ventes du jour',
    'Órdenes completadas': 'Commandes terminées',
    'Productos activos': 'Produits actifs',
    'Ventas:': 'Ventes :',
    'Gastos:': 'Dépenses :',
    'Beneficio:': 'Bénéfice :',
    'Margen:': 'Marge :',
    'Actividad de Empleados': 'Activité des Employés',
    'No hay datos de empleados disponibles': 'Aucune donnée d\'employé disponible',
    'Notificaciones Recientes': 'Notifications Récentes',
    'No hay notificaciones recientes': 'Aucune notification récente',
    'Ventas Diarias (Últimos 7 días)': 'Ventes Quotidiennes (7 derniers jours)',
    'Productos Más Vendidos': 'Produits les Plus Vendus',
    'No hay datos de ventas disponibles': 'Aucune donnée de vente disponible',
    'No hay datos de productos disponibles': 'Aucune donnée de produit disponible',
    'Insights de Rendimiento': 'Insights de Performance',

    // Sala - Room Management
    'Gestión de Sala': 'Gestion de la Salle',
    'Cargando mesas...': 'Chargement des tables...',
    'No se pudieron cargar las mesas': 'Impossible de charger les tables',
    'Error al cargar mesas': 'Erreur lors du chargement des tables',
    'Se agregaron 6 mesas por defecto': '6 tables par défaut ont été ajoutées',
    'No se pudieron agregar las mesas (requiere rol admin)': 'Impossible d\'ajouter les tables (nécessite le rôle admin)',
    'No se pudieron cargar los pedidos de la mesa': 'Impossible de charger les commandes de la table',
    'Mesa seleccionada para la orden': 'Table sélectionnée pour la commande',
    'No se pudo verificar el estado de la mesa': 'Impossible de vérifier l\'état de la table',
    'Seleccione una mesa primero': 'Sélectionnez d\'abord une table',
    'Pedido validado correctamente': 'Commande validée avec succès',
    'No se pudo validar el pedido': 'Impossible de valider la commande',
    'Orden marcada como para llevar': 'Commande marquée comme à emporter',
    'Mesa seleccionada:': 'Table sélectionnée :',
    'Añadir 6 mesas': 'Ajouter 6 tables',
    'No hay mesas configuradas': 'Aucune table configurée',
    'personas': 'personnes',
    'Disponible': 'Disponible',
    'Ocupada': 'Occupée',
    'Reservada': 'Réservée',
    'Sucia': 'Sale',
    'Pedidos en': 'Commandes à',
    'No hay pedidos en preparación para esta mesa.': 'Aucune commande en préparation pour cette table.',
    'Pedido': 'Commande',
    'Total:': 'Total :',
    'Continuar': 'Continuer',
    'Validar': 'Valider',
    'Cerrar': 'Fermer',
    'Confirmar Validación': 'Confirmer la Validation',
    'Continuando pedido existente': 'Poursuite de la commande existante',
    'Mesa': 'Table',

    // Orders Dashboard
    'Panel de Órdenes': 'Tableau des Commandes',
    'Órdenes Actuales': 'Commandes Actuelles',
    'Historial': 'Historique',
    'En Preparación': 'En Préparation',
    'Completado': 'Terminé',
    'Cancelado': 'Annulé',
    'Desde:': 'De :',
    'Hasta:': 'À :',
    'Filtrar': 'Filtrer',
    'Todos los usuarios': 'Tous les utilisateurs',
    'Mostrar últimas por orden': 'Afficher les dernières par commande',
    'Hoy:': 'Aujourd\'hui :',
    'Semana:': 'Semaine :',
    'Mes:': 'Mois :',
    'Hoy': 'Aujourd\'hui',
    'Esta Semana': 'Cette Semaine',
    'Este Mes': 'Ce Mois',
    'Todo': 'Tout',
    'Todos': 'Tous',
    'Aperturas': 'Ouvertures',
    'Cierres': 'Fermetures',
    'No hay órdenes para mostrar': 'Aucune commande à afficher',
    'Empleado:': 'Employé :',
    'Completar': 'Terminer',
    'Eliminar Pedido': 'Supprimer la Commande',
    'No hay historial de órdenes para mostrar': 'Aucun historique de commandes à afficher',
    'Orden': 'Commande',
    'Fecha': 'Date',
    'Estado': 'État',
    'Acción': 'Action',
    'Empleado': 'Employé',
    'Creada': 'Créée',
    'Actualizada': 'Mise à jour',
    'Completada': 'Terminée',
    'Cancelada': 'Annulée',
    'Seleccionar Método de Pago para Completar': 'Sélectionner le Mode de Paiement pour Terminer',
    'Completar Orden': 'Terminer la Commande',
    'Confirmar Eliminación': 'Confirmer la Suppression',
    'Esta acción no se puede deshacer. El pedido se moverá a órdenes eliminadas.': 'Cette action ne peut pas être annulée. La commande sera déplacée vers les commandes supprimées.',
    'Nota de eliminación (obligatoria):': 'Note de suppression (obligatoire) :',
    'Ingrese la razón de la eliminación...': 'Entrez la raison de la suppression...',
    'Eliminando...': 'Suppression...',
    'Confirmar Eliminación del Pedido': 'Confirmer la Suppression de la Commande',
    'No hay eventos de caja': 'Aucun événement de caisse',
    'Apertura': 'Ouverture',
    'Cierre': 'Fermeture',
    'Monto:': 'Montant :',
    'Nota:': 'Note :',
    '¿Está seguro de eliminar el pedido': 'Êtes-vous sûr de vouloir supprimer la commande',
    'Detalles del pedido:': 'Détails de la commande :',
    'caracteres': 'caractères',
    'Seleccionar Método de Pago': 'Sélectionner le Mode de Paiement',
    'Pago en efectivo': 'Paiement en espèces',
    'Pago con tarjeta': 'Paiement par carte',
    'Pago digital': 'Paiement numérique',
    'Error al actualizar el estado': 'Erreur lors de la mise à jour du statut',
    'Orden completada exitosamente': 'Commande terminée avec succès',
    'Error al completar la orden': 'Erreur lors de la finalisation de la commande',
    'Debe ingresar una nota de eliminación': 'Vous devez saisir une note de suppression',
    'Pedido eliminado correctamente': 'Commande supprimée avec succès',
    'Error al completar la orden:': 'Erreur lors de la finalisation de la commande :',
    'Error al eliminar pedido:': 'Erreur lors de la suppression de la commande :',

    // Products Manager
    'Gestión de Productos': 'Gestion des Produits',
    'Nuevo Producto': 'Nouveau Produit',
    'Crear': 'Créer',
    'Nombre': 'Nom',
    'Precio Base': 'Prix de Base',
    'Imagen (opcional)': 'Image (optionnelle)',
    'Vista previa': 'Aperçu',
    'Producto': 'Produit',
    'Tamaños': 'Tailles',
    'Único': 'Unique',
    'Sin categoría': 'Sans catégorie',
    'Disponible': 'Disponible',
    'No disponible': 'Non disponible',
    'Seleccionar categoría': 'Sélectionner une catégorie',
    'Error al crear producto': 'Erreur lors de la création du produit',
    'Subiendo imagen...': 'Téléchargement de l\'image...',
    'Error subiendo imagen:': 'Erreur lors du téléchargement de l\'image :',
    'Verifica el bucket "product-images" y permisos públicos.': 'Vérifiez le bucket "product-images" et les permissions publiques.',
    'Imagen subida correctamente': 'Image téléchargée avec succès',
    'No se pudo obtener la URL pública de la imagen.': 'Impossible d\'obtenir l\'URL publique de l\'image.',
    'Error durante la subida de imagen': 'Erreur lors du téléchargement de l\'image',
    'Producto creado correctamente': 'Produit créé avec succès',
    'Error al actualizar producto': 'Erreur lors de la mise à jour du produit',
    'Producto actualizado correctamente': 'Produit mis à jour avec succès',
    '¿Estás seguro de que deseas eliminar este producto?': 'Êtes-vous sûr de vouloir supprimer ce produit ?',
    'El producto será eliminado permanentemente de la lista de productos activos. Los pedidos históricos que contengan este producto se mantendrán intactos.': 'Le produit sera supprimé définitivement de la liste des produits actifs. Les commandes historiques contenant ce produit resteront intactes.',
    'Error al verificar el uso del producto': 'Erreur lors de la vérification de l\'utilisation du produit',
    'El producto aparece en el historial de pedidos, pero se eliminará correctamente.': 'Le produit apparaît dans l\'historique des commandes, mais sera supprimé correctement.',
    'Error al eliminar producto:': 'Erreur lors de la suppression du produit :',
    'Producto eliminado correctamente. El historial de pedidos se mantiene intacto.': 'Produit supprimé avec succès. L\'historique des commandes reste intact.',
    'Error al eliminar producto': 'Erreur lors de la suppression du produit',
    'Creando...': 'Création...',
    'Guardando cambios...': 'Enregistrement des modifications...',
    'Guardar cambios': 'Enregistrer les modifications',
    'Espera a que termine la operación': 'Attendez la fin de l\'opération',
    'Cancelar edición': 'Annuler la modification',
    'Editar producto': 'Modifier le produit',
    'Eliminar producto permanentemente': 'Supprimer le produit définitivement',

    // Category Manager
    'Gestión de Categorías': 'Gestion des Catégories',
    'Actualizar': 'Actualiser',
    'Actualizar lista': 'Actualiser la liste',
    'Editando Categoría': 'Modification de la Catégorie',
    'Nueva Categoría': 'Nouvelle Catégorie',
    'Nombre de la categoría': 'Nom de la catégorie',
    'Editando:': 'Modification :',
    'Guardando...': 'Enregistrement...',
    'Categorías Existentes': 'Catégories Existantes',
    'Error al cargar categorías:': 'Erreur lors du chargement des catégories :',
    'Error desconocido': 'Erreur inconnue',
    'Categoría actualizada correctamente': 'Catégorie mise à jour avec succès',
    'Categoría creada correctamente': 'Catégorie créée avec succès',
    'Error al guardar la categoría:': 'Erreur lors de l\'enregistrement de la catégorie :',
    '¿Estás seguro de eliminar la categoría': 'Êtes-vous sûr de vouloir supprimer la catégorie',
    'Esta acción no se puede deshacer.': 'Cette action ne peut pas être annulée.',
    'Error al verificar el uso de la categoría': 'Erreur lors de la vérification de l\'utilisation de la catégorie',
    'No se puede eliminar la categoría porque está siendo usada por': 'Impossible de supprimer la catégorie car elle est utilisée par',
    'producto(s). Elimine o reasigne los productos primero.': 'produit(s). Supprimez ou réassignez les produits d\'abord.',
    'Categoría eliminada correctamente': 'Catégorie supprimée avec succès',
    'Error al eliminar la categoría:': 'Erreur lors de la suppression de la catégorie :',
    'Cargando categorías...': 'Chargement des catégories...',
    'Modificando categoría:': 'Modification de la catégorie :',
    'Creada:': 'Créée :',
    'No hay categorías creadas': 'Aucune catégorie créée',
    'Editar categoría': 'Modifier la catégorie',
    'Eliminar categoría': 'Supprimer la catégorie',

    // User Manager
    'Gestión de Usuarios': 'Gestion des Utilisateurs',
    'Nuevo Empleado': 'Nouvel Employé',
    'Mostrar eliminados': 'Afficher les supprimés',
    'Mostrar inactivos': 'Afficher les inactifs',
    'Nombre Completo': 'Nom Complet',
    'Correo Electrónico': 'Adresse E-mail',
    'Contraseña': 'Mot de passe',
    'Teléfono': 'Téléphone',
    'Rol': 'Rôle',
    'Super Administrador': 'Super Administrateur',
    'Administrador': 'Administrateur',
    'Cajero': 'Caissier',
    'Barista': 'Barista',
    'Camarero': 'Serveur',
    'Crear Empleado': 'Créer un Employé',
    'Empleado': 'Employé',
    'Contacto': 'Contact',
    'Correo': 'E-mail',
    'Activo': 'Actif',
    'Inactivo': 'Inactif',
    'Eliminado': 'Supprimé',
    'Solo un Super Administrador puede crear otros Super Administradores': 'Seul un Super Administrateur peut créer d\'autres Super Administrateurs',
    'No se pudo crear el usuario': 'Impossible de créer l\'utilisateur',
    'Empleado creado exitosamente. Si la confirmación por email está habilitada, el usuario debe confirmar su correo.': 'Employé créé avec succès. Si la confirmation par e-mail est activée, l\'utilisateur doit confirmer son adresse e-mail.',
    'Error al crear empleado': 'Erreur lors de la création de l\'employé',
    'Usuario': 'Utilisateur',
    'desactivado': 'désactivé',
    'activado': 'activé',
    'Error al actualizar estado del empleado': 'Erreur lors de la mise à jour du statut de l\'employé',
    'Correo actualizado': 'E-mail mis à jour',
    'No se pudo actualizar el correo': 'Impossible de mettre à jour l\'e-mail',
    'Este usuario no tiene correo guardado': 'Cet utilisateur n\'a pas d\'e-mail enregistré',
    'Email de restablecimiento enviado': 'E-mail de réinitialisation envoyé',
    'No se pudo enviar el email de restablecimiento': 'Impossible d\'envoyer l\'e-mail de réinitialisation',
    'Eliminar lógicamente a': 'Supprimer logiquement',
    'Usuario eliminado (borrado lógico)': 'Utilisateur supprimé (suppression logique)',
    'No se pudo eliminar el usuario': 'Impossible de supprimer l\'utilisateur',
    'Error al cargar empleados': 'Erreur lors du chargement des employés',
    'No registrado': 'Non enregistré',
    'correo@ejemplo.com': 'email@exemple.com',
    'Usuario eliminado': 'Utilisateur supprimé',
    'Editar correo': 'Modifier l\'e-mail',
    'Guardar correo': 'Enregistrer l\'e-mail',
    'Enviar reset de contraseña': 'Envoyer la réinitialisation du mot de passe',
    'Sin correo': 'Sans e-mail',
    'Desactivar': 'Désactiver',
    'Activar': 'Activer',
    'Reset': 'Réinitialiser',
    'Guardar': 'Enregistrer',

    // Role Management
    'Gestión de Roles y Permisos': 'Gestion des Rôles et Permissions',
    'Configure los accesos para cada rol del sistema': 'Configurez les accès pour chaque rôle du système',
    'Cargando permisos...': 'Chargement des permissions...',
    'Error al cargar permisos': 'Erreur lors du chargement des permissions',
    'Permisos actualizados correctamente': 'Permissions mises à jour avec succès',
    'Error al guardar permisos': 'Erreur lors de l\'enregistrement des permissions',
    'Ventas': 'Ventes',
    'Inventario': 'Inventaire',
    'Finanzas': 'Finances',
    'Sistema': 'Système',
    'Órdenes': 'Commandes',
    'Usuarios': 'Utilisateurs',
    'Caja': 'Caisse',
    'Tiempo Empleados': 'Temps des Employés',
    'Proveedores': 'Fournisseurs',
    'Gastos': 'Dépenses',
    'Analíticas': 'Analytiques',
    'Productos': 'Produits',
    'Categorías': 'Catégories',
    'Gestión de Roles': 'Gestion des Rôles',
    'habilitadas': 'activées',
    'Acceso completo': 'Accès complet',
    'Acceso parcial': 'Accès partiel',
    'Sin acceso': 'Sans accès',
    'Permisos específicos:': 'Permissions spécifiques :',
    'Confirmar pedidos': 'Confirmer les commandes',
    'Validar pedidos (finalizar con pago)': 'Valider les commandes (finaliser avec paiement)',
    'Información sobre roles:': 'Informations sur les rôles :',
    'Acceso completo incluyendo gestión de roles': 'Accès complet incluant la gestion des rôles',
    'Acceso completo excepto gestión de roles': 'Accès complet sauf la gestion des rôles',
    'Ventas y gestión de caja': 'Ventes et gestion de caisse',
    'Solo sección de ventas': 'Section ventes uniquement',
    'Sala y órdenes (sin validar pedidos)': 'Salle et commandes (sans valider les commandes)',

    // App Settings
    'Configuración de la aplicación': 'Configuration de l\'application',
    'Personaliza el idioma y la apariencia de la aplicación. Los cambios se aplican inmediatamente.': 'Personnalisez la langue et l\'apparence de l\'application. Les modifications sont appliquées immédiatement.',
    'Español': 'Espagnol',
    'Français': 'Français',
    'Selecciona el tema de color de la aplicación': 'Sélectionnez le thème de couleur de l\'application',
    'Tema claro': 'Thème clair',
    'Tema oscuro': 'Thème sombre',
    'Automático': 'Automatique',
    'Información': 'Informations',
    'Los cambios de idioma se aplican inmediatamente a toda la aplicación': 'Les changements de langue sont appliqués immédiatement à toute l\'application',
    'La configuración se guarda automáticamente en tu navegador': 'La configuration est enregistrée automatiquement dans votre navigateur',
    'Puedes cambiar entre idiomas en cualquier momento': 'Vous pouvez changer de langue à tout moment',
    'El tema automático sigue la configuración de tu sistema operativo': 'Le thème automatique suit la configuration de votre système d\'exploitation',

    // Navigation & Cash Register
    'Ingrese un monto de cierre válido (>= 0)': 'Entrez un montant de clôture valide (>= 0)',
    'No hay sesión de caja abierta para cerrar. Se cerrará la sesión de usuario.': 'Aucune session de caisse ouverte à fermer. La session utilisateur sera fermée.',
    'Cierre de caja registrado e impreso.': 'Clôture de caisse enregistrée et imprimée.',
    'No se pudo cerrar la caja:': 'Impossible de fermer la caisse :',
    '¿Desea cerrar la sesión de caja antes de salir?': 'Voulez-vous fermer la session de caisse avant de quitter ?',
    'Monto de cierre': 'Montant de clôture',
    'Salir Sin Cambios': 'Quitter sans Modifications',
    'Cerrar Caja y Salir': 'Fermer la Caisse et Quitter',
    'CIERRE DE CAJA': 'CLÔTURE DE CAISSE',
    'Empleado:': 'Employé :',
    'SESIONES DEL DÍA': 'SESSIONS DU JOUR',
    'Sesión': 'Session',
    'RESUMEN FINANCIERO': 'RÉSUMÉ FINANCIER',
    'Primera Apertura:': 'Première Ouverture :',
    'Cierre Final:': 'Clôture Finale :',
    'Resultado del Día:': 'Résultat du Jour :',
    'Total Pedidos:': 'Total Commandes :',
    'Total Ventas:': 'Total Ventes :',
    'PEDIDOS DEL DÍA': 'COMMANDES DU JOUR',
    'Pedido #': 'Commande n°',
    'Hora:': 'Heure :',
    'Producto': 'Produit',
    'Generado el': 'Généré le',
    'El cambio de idioma se aplicará a todos los usuarios del sistema de forma inmediata.': 'Le changement de langue sera appliqué à tous les utilisateurs du système immédiatement.',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('es');
  const [isLoading, setIsLoading] = useState(true);

  // Cargar idioma desde la base de datos al iniciar
  useEffect(() => {
    const loadLanguageFromDB = async () => {
      try {
        console.log('🔄 [LANGUAGE] Loading language from database...');
        const { data, error } = await supabase
          .from('company_settings')
          .select('language')
          .single();

        if (error) {
          console.error('❌ [LANGUAGE] Error loading language from DB:', error);
          // Si hay error, usar idioma por defecto
          setCurrentLanguage('es');
          console.log('⚠️ [LANGUAGE] Using default language: es');
        } else if (data && data.language) {
          console.log(`✅ [LANGUAGE] Loaded language from DB: ${data.language}`);
          setCurrentLanguage(data.language as Language);
          document.documentElement.lang = data.language;
        } else {
          // Si no hay idioma configurado, usar español por defecto
          console.log('⚠️ [LANGUAGE] No language configured, using default: es');
          setCurrentLanguage('es');
        }
      } catch (error) {
        console.error('💥 [LANGUAGE] Error loading language:', error);
        setCurrentLanguage('es');
      } finally {
        setIsLoading(false);
      }
    };

    loadLanguageFromDB();

    // Suscribirse a cambios en tiempo real en company_settings
    console.log('📡 [LANGUAGE] Setting up Realtime subscription...');
    const channel = supabase
      .channel('company-settings-language')
      .on(
        'postgres_changes',
        {
          event: 'UPDATE',
          schema: 'public',
          table: 'company_settings'
        },
        (payload) => {
          console.log('🔔 [LANGUAGE] Realtime change detected!', payload);
          if (payload.new && (payload.new as any).language) {
            const newLanguage = (payload.new as any).language as Language;
            console.log(`🌍 [LANGUAGE] Updating language to: ${newLanguage} (from Realtime)`);
            setCurrentLanguage(newLanguage);
            document.documentElement.lang = newLanguage;
            console.log(`✅ [LANGUAGE] Language updated successfully to: ${newLanguage}`);
          }
        }
      )
      .subscribe((status) => {
        console.log(`📡 [LANGUAGE] Realtime subscription status: ${status}`);
      });

    return () => {
      console.log('🔌 [LANGUAGE] Disconnecting Realtime subscription...');
      supabase.removeChannel(channel);
    };
  }, []);

  const setLanguage = async (lang: Language) => {
    try {
      console.log(`🌍 [LANGUAGE] Attempting to change language to: ${lang}`);

      // Primero obtener el ID de company_settings
      const { data: settingsData, error: fetchError } = await supabase
        .from('company_settings')
        .select('id')
        .single();

      if (fetchError) {
        console.error('❌ [LANGUAGE] Error fetching company_settings ID:', fetchError);
        throw fetchError;
      }

      if (!settingsData) {
        console.error('❌ [LANGUAGE] No company_settings record found');
        throw new Error('No company_settings record found');
      }

      console.log(`📝 [LANGUAGE] Updating company_settings (ID: ${settingsData.id}) to language: ${lang}`);

      // Actualizar en la base de datos (esto notificará a todos los clientes conectados)
      const { error: updateError } = await supabase
        .from('company_settings')
        .update({ language: lang })
        .eq('id', settingsData.id);

      if (updateError) {
        console.error('❌ [LANGUAGE] Error updating language in DB:', updateError);
        throw updateError;
      }

      console.log(`✅ [LANGUAGE] Language updated to ${lang} in database`);

      // Actualizar inmediatamente en el cliente
      setCurrentLanguage(lang);
      document.documentElement.lang = lang;

      console.log(`✅ [LANGUAGE] Language updated to ${lang} in local state`);
    } catch (error) {
      console.error('💥 [LANGUAGE] Error setting language:', error);
      // Revertir el cambio cargando desde la base de datos
      const { data } = await supabase.from('company_settings').select('language').single();
      if (data && data.language) {
        setCurrentLanguage(data.language as Language);
        document.documentElement.lang = data.language;
      }
      throw error; // Re-lanzar el error para que AppSettings pueda manejarlo
    }
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations.es] || key;
  };

  // Mostrar un loader mientras se carga el idioma
  if (isLoading) {
    return null; // o un spinner si prefieres
  }

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}