import { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'fr';

export interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Traducciones básicas de la aplicación
const translations = {
  es: {
    // Navegación
    'nav.sales': 'Ventas',
    'nav.inventory': 'Inventario',
    'nav.finance': 'Finanzas',
    'nav.system': 'Sistema',
    'nav.floor': 'Sala',
    'nav.pos': 'Punto de Venta',
    'nav.orders': 'Órdenes',
    'nav.products': 'Productos',
    'nav.categories': 'Categorías',
    'nav.users': 'Usuarios',
    'nav.cash': 'Caja',
    'nav.time-tracking': 'Tiempo Empleados',
    'nav.suppliers': 'Proveedores',
    'nav.expenses': 'Gastos',
    'nav.analytics': 'Analíticas',
    'nav.role-management': 'Gestión de Roles',
    'nav.company-settings': 'Información Empresa',
    'nav.app-settings': 'Configuración',

    // Acciones comunes
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.add': 'Agregar',
    'common.search': 'Buscar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',

    // Configuración
    'settings.language': 'Idioma',
    'settings.language.es': 'Español',
    'settings.language.fr': 'Francés',
    'settings.language.description': 'Selecciona el idioma de la aplicación',
    'settings.general': 'Configuración General',
    'settings.general.description': 'Personaliza el comportamiento de la aplicación',
    'settings.theme': 'Tema',
    'settings.theme.light': 'Claro',
    'settings.theme.dark': 'Oscuro',
    'settings.theme.auto': 'Automático',

    // Mensajes
    'messages.language-changed': 'Idioma cambiado correctamente',
    'messages.settings-saved': 'Configuración guardada correctamente',

    // Configuración empresa
    'Información de la Empresa': 'Información de la Empresa',
    'Configure los datos que aparecen en tickets y reportes': 'Configure los datos que aparecen en tickets y reportes',
    'Esta información aparecerá en:': 'Esta información aparecerá en:',
    'Todos los tickets de venta impresos': 'Todos los tickets de venta impresos',
    'Reportes Excel exportados desde Analíticas': 'Reportes Excel exportados desde Analíticas',
    'Reportes de tiempo de empleados': 'Reportes de tiempo de empleados',
    'Cualquier documento generado por el sistema': 'Cualquier documento generado por el sistema',
    'Nombre de la Empresa': 'Nombre de la Empresa',
    'Dirección': 'Dirección',
    'Número de Teléfono': 'Número de Teléfono',
    'Guardar Cambios': 'Guardar Cambios',
    'Deshacer': 'Deshacer',
    'Vista Previa (Tickets)': 'Vista Previa (Tickets)',
    'Información de pedido...': 'Información de pedido...',
    'Este nombre aparecerá en todos los documentos': 'Este nombre aparecerá en todos los documentos',
    'Dirección física de la empresa': 'Dirección física de la empresa',
    'Número de contacto para clientes': 'Número de contacto para clientes',

    // Sistema de Gestión
    'Sistema de Gestión': 'Sistema de Gestión',
    'Menú de Navegación': 'Menú de Navegación',
    'Menú Admin': 'Menú Admin',
    'Salir': 'Salir',
    'Cerrar Sesión': 'Cerrar Sesión',
    'Sala': 'Sala',
    'Pedidos': 'Pedidos',
    'Punto de Venta': 'Punto de Venta',
    'Apertura de Caja': 'Apertura de Caja',
    'Indique el monto inicial en caja para comenzar su turno.': 'Indique el monto inicial en caja para comenzar su turno.',
    'Cierre de Caja': 'Cierre de Caja',
    'Indique el monto final en caja antes de cerrar sesión.': 'Indique el monto final en caja antes de cerrar sesión.',

    // POS - Punto de Venta
    'Cargando productos...': 'Cargando productos...',
    'Reintentar': 'Reintentar',
    'Todos': 'Todos',
    'Agregar': 'Agregar',
    'Agregar al carrito': 'Agregar al carrito',
    'Cargar más productos': 'Cargar más productos',
    'Carrito de Compras': 'Carrito de Compras',
    'El carrito está vacío': 'El carrito está vacío',
    'Selecciona productos para comenzar': 'Selecciona productos para comenzar',
    'Para llevar': 'Para llevar',
    'En sala': 'En sala',
    'Seleccione mesa': 'Seleccione mesa',
    'Confirmar Pedido': 'Confirmar Pedido',
    'Seleccionar Método de Pago': 'Seleccionar Método de Pago',
    'Efectivo': 'Efectivo',
    'Pago en efectivo': 'Pago en efectivo',
    'Tarjeta': 'Tarjeta',
    'Pago con tarjeta': 'Pago con tarjeta',
    'Digital': 'Digital',
    'Pago digital': 'Pago digital',
    'Cancelar': 'Cancelar',
    'Total del Pedido:': 'Total del Pedido:',
    'Método de Pago:': 'Método de Pago:',
    'Después': 'Después',
    'Validar e Imprimir': 'Validar e Imprimir',

    // Sala - Room Management
    'Gestión de Sala': 'Gestión de Sala',
    'Sala': 'Sala',
    'Cargando mesas...': 'Cargando mesas...',
    'No se pudieron cargar las mesas': 'No se pudieron cargar las mesas',
    'Error al cargar mesas': 'Error al cargar mesas',
    'Se agregaron 6 mesas por defecto': 'Se agregaron 6 mesas por defecto',
    'No se pudieron agregar las mesas (requiere rol admin)': 'No se pudieron agregar las mesas (requiere rol admin)',
    'No se pudieron cargar los pedidos de la mesa': 'No se pudieron cargar los pedidos de la mesa',
    'Mesa seleccionada para la orden': 'Mesa seleccionada para la orden',
    'No se pudo verificar el estado de la mesa': 'No se pudo verificar el estado de la mesa',
    'Seleccione una mesa primero': 'Seleccione una mesa primero',
    'Pedido validado correctamente': 'Pedido validado correctamente',
    'No se pudo validar el pedido': 'No se pudo validar el pedido',
    'Orden marcada como para llevar': 'Orden marcada como para llevar',
    'Mesa seleccionada:': 'Mesa seleccionada:',
    'Añadir 6 mesas': 'Añadir 6 mesas',
    'No hay mesas configuradas': 'No hay mesas configuradas',
    'personas': 'personas',
    'Disponible': 'Disponible',
    'Ocupada': 'Ocupada',
    'Reservada': 'Reservada',
    'Sucia': 'Sucia',
    'Pedidos en': 'Pedidos en',
    'No hay pedidos en preparación para esta mesa.': 'No hay pedidos en preparación para esta mesa.',
    'Pedido': 'Pedido',
    'Total:': 'Total:',
    'Continuar': 'Continuar',
    'Validar': 'Validar',
    'Cerrar': 'Cerrar',
    'Confirmar Validación': 'Confirmar Validación',
    'Continuando pedido existente': 'Continuando pedido existente',
    'Mesa': 'Mesa',

    // Orders Dashboard
    'Panel de Órdenes': 'Panel de Órdenes',
    'Órdenes Actuales': 'Órdenes Actuales',
    'Historial': 'Historial',
    'En Preparación': 'En Preparación',
    'Completado': 'Completado',
    'Cancelado': 'Cancelado',
    'Desde:': 'Desde:',
    'Hasta:': 'Hasta:',
    'Filtrar': 'Filtrar',
    'Todos los usuarios': 'Todos los usuarios',
    'Mostrar últimas por orden': 'Mostrar últimas por orden',
    'Hoy:': 'Hoy:',
    'Semana:': 'Semana:',
    'Mes:': 'Mes:',
    'Hoy': 'Hoy',
    'Esta Semana': 'Esta Semana',
    'Este Mes': 'Este Mes',
    'Todo': 'Todo',
    'Todos': 'Todos',
    'Aperturas': 'Aperturas',
    'Cierres': 'Cierres',
    'No hay órdenes para mostrar': 'No hay órdenes para mostrar',
    'Empleado:': 'Empleado:',
    'Completar': 'Completar',
    'Eliminar Pedido': 'Eliminar Pedido',
    'No hay historial de órdenes para mostrar': 'No hay historial de órdenes para mostrar',
    'Orden': 'Orden',
    'Fecha': 'Fecha',
    'Estado': 'Estado',
    'Acción': 'Acción',
    'Empleado': 'Empleado',
    'Creada': 'Creada',
    'Actualizada': 'Actualizada',
    'Completada': 'Completada',
    'Cancelada': 'Cancelada',
    'Seleccionar Método de Pago para Completar': 'Seleccionar Método de Pago para Completar',
    'Completar Orden': 'Completar Orden',
    'Confirmar Eliminación': 'Confirmar Eliminación',
    'Esta acción no se puede deshacer. El pedido se moverá a órdenes eliminadas.': 'Esta acción no se puede deshacer. El pedido se moverá a órdenes eliminadas.',
    'Nota de eliminación (obligatoria):': 'Nota de eliminación (obligatoria):',
    'Ingrese la razón de la eliminación...': 'Ingrese la razón de la eliminación...',
    'Eliminando...': 'Eliminando...',
    'Confirmar Eliminación del Pedido': 'Confirmar Eliminación del Pedido',
    'No hay eventos de caja': 'No hay eventos de caja',
    'Apertura': 'Apertura',
    'Cierre': 'Cierre',
    'Monto:': 'Monto:',
    'Nota:': 'Nota:',
    '¿Está seguro de eliminar el pedido': '¿Está seguro de eliminar el pedido',
    'Detalles del pedido:': 'Detalles del pedido:',
    'caracteres': 'caracteres',
    'Seleccionar Método de Pago': 'Seleccionar Método de Pago',
    'Pago en efectivo': 'Pago en efectivo',
    'Pago con tarjeta': 'Pago con tarjeta',
    'Pago digital': 'Pago digital',
    'Error al actualizar el estado': 'Error al actualizar el estado',
    'Orden completada exitosamente': 'Orden completada exitosamente',
    'Error al completar la orden': 'Error al completar la orden',
    'Debe ingresar una nota de eliminación': 'Debe ingresar una nota de eliminación',
    'Pedido eliminado correctamente': 'Pedido eliminado correctamente',
    'Error al completar la orden:': 'Error al completar la orden:',
    'Error al eliminar pedido:': 'Error al eliminar pedido:',

    // Products Manager
    'Gestión de Productos': 'Gestión de Productos',
    'Nuevo Producto': 'Nuevo Producto',
    'Crear': 'Crear',
    'Nombre': 'Nombre',
    'Precio Base': 'Precio Base',
    'Imagen (opcional)': 'Imagen (opcional)',
    'Vista previa': 'Vista previa',
    'Producto': 'Producto',
    'Tamaños': 'Tamaños',
    'Único': 'Único',
    'Sin categoría': 'Sin categoría',
    'Disponible': 'Disponible',
    'No disponible': 'No disponible',
    'Seleccionar categoría': 'Seleccionar categoría',
    'Error al crear producto': 'Error al crear producto',
    'Subiendo imagen...': 'Subiendo imagen...',
    'Error subiendo imagen:': 'Error subiendo imagen:',
    'Verifica el bucket "product-images" y permisos públicos.': 'Verifica el bucket "product-images" y permisos públicos.',
    'Imagen subida correctamente': 'Imagen subida correctamente',
    'No se pudo obtener la URL pública de la imagen.': 'No se pudo obtener la URL pública de la imagen.',
    'Error durante la subida de imagen': 'Error durante la subida de imagen',
    'Producto creado correctamente': 'Producto creado correctamente',
    'Error al actualizar producto': 'Error al actualizar producto',
    'Producto actualizado correctamente': 'Producto actualizado correctamente',
    '¿Estás seguro de que deseas eliminar este producto?': '¿Estás seguro de que deseas eliminar este producto?',
    'El producto será eliminado permanentemente de la lista de productos activos. Los pedidos históricos que contengan este producto se mantendrán intactos.': 'El producto será eliminado permanentemente de la lista de productos activos. Los pedidos históricos que contengan este producto se mantendrán intactos.',
    'Error al verificar el uso del producto': 'Error al verificar el uso del producto',
    'El producto aparece en el historial de pedidos, pero se eliminará correctamente.': 'El producto aparece en el historial de pedidos, pero se eliminará correctamente.',
    'Error al eliminar producto:': 'Error al eliminar producto:',
    'Producto eliminado correctamente. El historial de pedidos se mantiene intacto.': 'Producto eliminado correctamente. El historial de pedidos se mantiene intacto.',
    'Error al eliminar producto': 'Error al eliminar producto',
    'Creando...': 'Creando...',
    'Guardando cambios...': 'Guardando cambios...',
    'Guardar cambios': 'Guardar cambios',
    'Espera a que termine la operación': 'Espera a que termine la operación',
    'Cancelar edición': 'Cancelar edición',
    'Editar producto': 'Editar producto',
    'Eliminar producto permanentemente': 'Eliminar producto permanentemente',

    // Category Manager
    'Gestión de Categorías': 'Gestión de Categorías',
    'Actualizar': 'Actualizar',
    'Actualizar lista': 'Actualizar lista',
    'Editando Categoría': 'Editando Categoría',
    'Nueva Categoría': 'Nueva Categoría',
    'Nombre de la categoría': 'Nombre de la categoría',
    'Editando:': 'Editando:',
    'Guardando...': 'Guardando...',
    'Categorías Existentes': 'Categorías Existentes',
    'Error al cargar categorías:': 'Error al cargar categorías:',
    'Error desconocido': 'Error desconocido',
    'Categoría actualizada correctamente': 'Categoría actualizada correctamente',
    'Categoría creada correctamente': 'Categoría creada correctamente',
    'Error al guardar la categoría:': 'Error al guardar la categoría:',
    '¿Estás seguro de eliminar la categoría': '¿Estás seguro de eliminar la categoría',
    'Esta acción no se puede deshacer.': 'Esta acción no se puede deshacer.',
    'Error al verificar el uso de la categoría': 'Error al verificar el uso de la categoría',
    'No se puede eliminar la categoría porque está siendo usada por': 'No se puede eliminar la categoría porque está siendo usada por',
    'producto(s). Elimine o reasigne los productos primero.': 'producto(s). Elimine o reasigne los productos primero.',
    'Categoría eliminada correctamente': 'Categoría eliminada correctamente',
    'Error al eliminar la categoría:': 'Error al eliminar la categoría:',
    'Cargando categorías...': 'Cargando categorías...',
    'Modificando categoría:': 'Modificando categoría:',
    'Creada:': 'Creada:',
    'No hay categorías creadas': 'No hay categorías creadas',
    'Editar categoría': 'Editar categoría',
    'Eliminar categoría': 'Eliminar categoría',

    // User Manager
    'Gestión de Usuarios': 'Gestión de Usuarios',
    'Nuevo Empleado': 'Nuevo Empleado',
    'Mostrar eliminados': 'Mostrar eliminados',
    'Mostrar inactivos': 'Mostrar inactivos',
    'Nombre Completo': 'Nombre Completo',
    'Correo Electrónico': 'Correo Electrónico',
    'Contraseña': 'Contraseña',
    'Teléfono': 'Teléfono',
    'Rol': 'Rol',
    'Super Administrador': 'Super Administrador',
    'Administrador': 'Administrador',
    'Cajero': 'Cajero',
    'Barista': 'Barista',
    'Camarero': 'Camarero',
    'Crear Empleado': 'Crear Empleado',
    'Empleado': 'Empleado',
    'Contacto': 'Contacto',
    'Correo': 'Correo',
    'Activo': 'Activo',
    'Inactivo': 'Inactivo',
    'Eliminado': 'Eliminado',
    'Solo un Super Administrador puede crear otros Super Administradores': 'Solo un Super Administrador puede crear otros Super Administradores',
    'No se pudo crear el usuario': 'No se pudo crear el usuario',
    'Empleado creado exitosamente. Si la confirmación por email está habilitada, el usuario debe confirmar su correo.': 'Empleado creado exitosamente. Si la confirmación por email está habilitada, el usuario debe confirmar su correo.',
    'Error al crear empleado': 'Error al crear empleado',
    'Usuario': 'Usuario',
    'desactivado': 'desactivado',
    'activado': 'activado',
    'Error al actualizar estado del empleado': 'Error al actualizar estado del empleado',
    'Correo actualizado': 'Correo actualizado',
    'No se pudo actualizar el correo': 'No se pudo actualizar el correo',
    'Este usuario no tiene correo guardado': 'Este usuario no tiene correo guardado',
    'Email de restablecimiento enviado': 'Email de restablecimiento enviado',
    'No se pudo enviar el email de restablecimiento': 'No se pudo enviar el email de restablecimiento',
    'Eliminar lógicamente a': 'Eliminar lógicamente a',
    'Usuario eliminado (borrado lógico)': 'Usuario eliminado (borrado lógico)',
    'No se pudo eliminar el usuario': 'No se pudo eliminar el usuario',
    'Error al cargar empleados': 'Error al cargar empleados',
    'No registrado': 'No registrado',
    'correo@ejemplo.com': 'correo@ejemplo.com',
    'Usuario eliminado': 'Usuario eliminado',
    'Editar correo': 'Editar correo',
    'Guardar correo': 'Guardar correo',
    'Enviar reset de contraseña': 'Enviar reset de contraseña',
    'Sin correo': 'Sin correo',
    'Desactivar': 'Desactivar',
    'Activar': 'Activar',
    'Reset': 'Reset',
    'Guardar': 'Guardar',
  },
  fr: {
    // Navigation
    'nav.sales': 'Ventes',
    'nav.inventory': 'Inventaire',
    'nav.finance': 'Finances',
    'nav.system': 'Système',
    'nav.floor': 'Salle',
    'nav.pos': 'Point de Vente',
    'nav.orders': 'Commandes',
    'nav.products': 'Produits',
    'nav.categories': 'Catégories',
    'nav.users': 'Utilisateurs',
    'nav.cash': 'Caisse',
    'nav.time-tracking': 'Temps Employés',
    'nav.suppliers': 'Fournisseurs',
    'nav.expenses': 'Dépenses',
    'nav.analytics': 'Analytiques',
    'nav.role-management': 'Gestion des Rôles',
    'nav.company-settings': 'Informations Entreprise',
    'nav.app-settings': 'Configuration',

    // Actions communes
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.add': 'Ajouter',
    'common.search': 'Rechercher',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',

    // Configuration
    'settings.language': 'Langue',
    'settings.language.es': 'Espagnol',
    'settings.language.fr': 'Français',
    'settings.language.description': 'Sélectionnez la langue de l\'application',
    'settings.general': 'Configuration Générale',
    'settings.general.description': 'Personnalisez le comportement de l\'application',
    'settings.theme': 'Thème',
    'settings.theme.light': 'Clair',
    'settings.theme.dark': 'Sombre',
    'settings.theme.auto': 'Automatique',

    // Messages
    'messages.language-changed': 'Langue changée avec succès',
    'messages.settings-saved': 'Configuration sauvegardée avec succès',

    // Configuration entreprise
    'Información de la Empresa': 'Informations de l\'Entreprise',
    'Configure los datos que aparecen en tickets y reportes': 'Configurez les données qui apparaissent sur les tickets et rapports',
    'Esta información aparecerá en:': 'Ces informations apparaîtront dans :',
    'Todos los tickets de venta impresos': 'Tous les tickets de vente imprimés',
    'Reportes Excel exportados desde Analíticas': 'Rapports Excel exportés depuis Analytics',
    'Reportes de tiempo de empleados': 'Rapports de temps des employés',
    'Cualquier documento generado por el sistema': 'Tout document généré par le système',
    'Nombre de la Empresa': 'Nom de l\'Entreprise',
    'Dirección': 'Adresse',
    'Número de Teléfono': 'Numéro de Téléphone',
    'Guardar Cambios': 'Enregistrer les Modifications',
    'Deshacer': 'Annuler',
    'Vista Previa (Tickets)': 'Aperçu (Tickets)',
    'Información de pedido...': 'Informations de commande...',
    'Este nombre aparecerá en todos los documentos': 'Ce nom apparaîtra sur tous les documents',
    'Dirección física de la empresa': 'Adresse physique de l\'entreprise',
    'Número de contacto para clientes': 'Numéro de contact pour les clients',

    // Système de Gestion
    'Sistema de Gestión': 'Système de Gestion',
    'Menú de Navegación': 'Menu de Navigation',
    'Menú Admin': 'Menu Admin',
    'Salir': 'Quitter',
    'Cerrar Sesión': 'Fermer la Session',
    'Sala': 'Salle',
    'Pedidos': 'Commandes',
    'Punto de Venta': 'Point de Vente',
    'Apertura de Caja': 'Ouverture de Caisse',
    'Indique el monto inicial en caja para comenzar su turno.': 'Indiquez le montant initial en caisse pour commencer votre service.',
    'Cierre de Caja': 'Fermeture de Caisse',
    'Indique el monto final en caja antes de cerrar sesión.': 'Indiquez le montant final en caisse avant de fermer la session.',

    // POS - Punto de Venta
    'Cargando productos...': 'Chargement des produits...',
    'Reintentar': 'Réessayer',
    'Todos': 'Tous',
    'Agregar': 'Ajouter',
    'Agregar al carrito': 'Ajouter au panier',
    'Cargar más productos': 'Charger plus de produits',
    'Carrito de Compras': 'Panier d\'Achats',
    'El carrito está vacío': 'Le panier est vide',
    'Selecciona productos para comenzar': 'Sélectionnez des produits pour commencer',
    'Para llevar': 'À emporter',
    'En sala': 'En salle',
    'Seleccione mesa': 'Sélectionnez une table',
    'Confirmar Pedido': 'Confirmer la Commande',
    'Seleccionar Método de Pago': 'Sélectionner le Mode de Paiement',
    'Efectivo': 'Espèces',
    'Pago en efectivo': 'Paiement en espèces',
    'Tarjeta': 'Carte',
    'Pago con tarjeta': 'Paiement par carte',
    'Digital': 'Numérique',
    'Pago digital': 'Paiement numérique',
    'Cancelar': 'Annuler',
    'Total del Pedido:': 'Total de la Commande :',
    'Método de Pago:': 'Mode de Paiement :',
    'Después': 'Après',
    'Validar e Imprimir': 'Valider et Imprimer',

    // Login Form
    'Correo Electrónico': 'Adresse e-mail',
    'Contraseña': 'Mot de passe',
    'Iniciando sesión...': 'Connexion en cours...',
    'Iniciar Sesión': 'Se connecter',

    // Role Management
    'Gestión de Roles y Permisos': 'Gestion des Rôles et Permissions',
    'Configure los accesos para cada rol del sistema': 'Configurez les accès pour chaque rôle du système',
    'Cargando permisos...': 'Chargement des permissions...',

    // Role Management
    'Gestión de Roles y Permisos': 'Gestion des Rôles et Permissions',
    'Configure los accesos para cada rol del sistema': 'Configurez les accès pour chaque rôle du système',
    'Cargando permisos...': 'Chargement des permissions...',

    // Analytics
    'Analíticas y Reportes': 'Analyses et Rapports',
    'usuarios conectados': 'utilisateurs connectés',
    'mesas ocupadas': 'tables occupées',
    'Exportar Excel': 'Exporter Excel',
    'Ventas del día': 'Ventes du jour',
    'Órdenes completadas': 'Commandes terminées',
    'Productos activos': 'Produits actifs',
    'Ventas:': 'Ventes :',
    'Gastos:': 'Dépenses :',
    'Beneficio:': 'Bénéfice :',
    'Margen:': 'Marge :',
    'Actividad de Empleados': 'Activité des Employés',
    'No hay datos de empleados disponibles': 'Aucune donnée d\'employé disponible',
    'Notificaciones Recientes': 'Notifications Récentes',
    'No hay notificaciones recientes': 'Aucune notification récente',
    'Ventas Diarias (Últimos 7 días)': 'Ventes Quotidiennes (7 derniers jours)',
    'Productos Más Vendidos': 'Produits les Plus Vendus',
    'No hay datos de ventas disponibles': 'Aucune donnée de vente disponible',
    'No hay datos de productos disponibles': 'Aucune donnée de produit disponible',
    'Insights de Rendimiento': 'Insights de Performance',

    // Login Form
    'Correo Electrónico': 'Adresse e-mail',
    'Contraseña': 'Mot de passe',
    'Iniciando sesión...': 'Connexion en cours...',
    'Iniciar Sesión': 'Se connecter',

    // Sala - Room Management
    'Gestión de Sala': 'Gestion de la Salle',
    'Sala': 'Salle',
    'Cargando mesas...': 'Chargement des tables...',
    'No se pudieron cargar las mesas': 'Impossible de charger les tables',
    'Error al cargar mesas': 'Erreur lors du chargement des tables',
    'Se agregaron 6 mesas por defecto': '6 tables par défaut ont été ajoutées',
    'No se pudieron agregar las mesas (requiere rol admin)': 'Impossible d\'ajouter les tables (nécessite le rôle admin)',
    'No se pudieron cargar los pedidos de la mesa': 'Impossible de charger les commandes de la table',
    'Mesa seleccionada para la orden': 'Table sélectionnée pour la commande',
    'No se pudo verificar el estado de la mesa': 'Impossible de vérifier l\'état de la table',
    'Seleccione una mesa primero': 'Sélectionnez d\'abord une table',
    'Pedido validado correctamente': 'Commande validée avec succès',
    'No se pudo validar el pedido': 'Impossible de valider la commande',
    'Orden marcada como para llevar': 'Commande marquée comme à emporter',
    'Mesa seleccionada:': 'Table sélectionnée :',
    'Añadir 6 mesas': 'Ajouter 6 tables',
    'No hay mesas configuradas': 'Aucune table configurée',
    'personas': 'personnes',
    'Disponible': 'Disponible',
    'Ocupada': 'Occupée',
    'Reservada': 'Réservée',
    'Sucia': 'Sale',
    'Pedidos en': 'Commandes à',
    'No hay pedidos en preparación para esta mesa.': 'Aucune commande en préparation pour cette table.',
    'Pedido': 'Commande',
    'Total:': 'Total :',
    'Continuar': 'Continuer',
    'Validar': 'Valider',
    'Cerrar': 'Fermer',
    'Confirmar Validación': 'Confirmer la Validation',
    'Continuando pedido existente': 'Poursuite de la commande existante',
    'Mesa': 'Table',

    // Orders Dashboard
    'Panel de Órdenes': 'Tableau des Commandes',
    'Órdenes Actuales': 'Commandes Actuelles',
    'Historial': 'Historique',
    'En Preparación': 'En Préparation',
    'Completado': 'Terminé',
    'Cancelado': 'Annulé',
    'Desde:': 'De :',
    'Hasta:': 'À :',
    'Filtrar': 'Filtrer',
    'Todos los usuarios': 'Tous les utilisateurs',
    'Mostrar últimas por orden': 'Afficher les dernières par commande',
    'Hoy:': 'Aujourd\'hui :',
    'Semana:': 'Semaine :',
    'Mes:': 'Mois :',
    'Hoy': 'Aujourd\'hui',
    'Esta Semana': 'Cette Semaine',
    'Este Mes': 'Ce Mois',
    'Todo': 'Tout',
    'Todos': 'Tous',
    'Aperturas': 'Ouvertures',
    'Cierres': 'Fermetures',
    'No hay órdenes para mostrar': 'Aucune commande à afficher',
    'Empleado:': 'Employé :',
    'Completar': 'Terminer',
    'Eliminar Pedido': 'Supprimer la Commande',
    'No hay historial de órdenes para mostrar': 'Aucun historique de commandes à afficher',
    'Orden': 'Commande',
    'Fecha': 'Date',
    'Estado': 'État',
    'Acción': 'Action',
    'Empleado': 'Employé',
    'Creada': 'Créée',
    'Actualizada': 'Mise à jour',
    'Completada': 'Terminée',
    'Cancelada': 'Annulée',
    'Seleccionar Método de Pago para Completar': 'Sélectionner le Mode de Paiement pour Terminer',
    'Completar Orden': 'Terminer la Commande',
    'Confirmar Eliminación': 'Confirmer la Suppression',
    'Esta acción no se puede deshacer. El pedido se moverá a órdenes eliminadas.': 'Cette action ne peut pas être annulée. La commande sera déplacée vers les commandes supprimées.',
    'Nota de eliminación (obligatoria):': 'Note de suppression (obligatoire) :',
    'Ingrese la razón de la eliminación...': 'Entrez la raison de la suppression...',
    'Eliminando...': 'Suppression...',
    'Confirmar Eliminación del Pedido': 'Confirmer la Suppression de la Commande',
    'No hay eventos de caja': 'Aucun événement de caisse',
    'Apertura': 'Ouverture',
    'Cierre': 'Fermeture',
    'Monto:': 'Montant :',
    'Nota:': 'Note :',
    '¿Está seguro de eliminar el pedido': 'Êtes-vous sûr de vouloir supprimer la commande',
    'Detalles del pedido:': 'Détails de la commande :',
    'caracteres': 'caractères',
    'Seleccionar Método de Pago': 'Sélectionner le Mode de Paiement',
    'Pago en efectivo': 'Paiement en espèces',
    'Pago con tarjeta': 'Paiement par carte',
    'Pago digital': 'Paiement numérique',
    'Error al actualizar el estado': 'Erreur lors de la mise à jour du statut',
    'Orden completada exitosamente': 'Commande terminée avec succès',
    'Error al completar la orden': 'Erreur lors de la finalisation de la commande',
    'Debe ingresar una nota de eliminación': 'Vous devez saisir une note de suppression',
    'Pedido eliminado correctamente': 'Commande supprimée avec succès',
    'Error al completar la orden:': 'Erreur lors de la finalisation de la commande :',
    'Error al eliminar pedido:': 'Erreur lors de la suppression de la commande :',

    // Products Manager
    'Gestión de Productos': 'Gestion des Produits',
    'Nuevo Producto': 'Nouveau Produit',
    'Crear': 'Créer',
    'Nombre': 'Nom',
    'Precio Base': 'Prix de Base',
    'Imagen (opcional)': 'Image (optionnelle)',
    'Vista previa': 'Aperçu',
    'Producto': 'Produit',
    'Tamaños': 'Tailles',
    'Único': 'Unique',
    'Sin categoría': 'Sans catégorie',
    'Disponible': 'Disponible',
    'No disponible': 'Non disponible',
    'Seleccionar categoría': 'Sélectionner une catégorie',
    'Error al crear producto': 'Erreur lors de la création du produit',
    'Subiendo imagen...': 'Téléchargement de l\'image...',
    'Error subiendo imagen:': 'Erreur lors du téléchargement de l\'image :',
    'Verifica el bucket "product-images" y permisos públicos.': 'Vérifiez le bucket "product-images" et les permissions publiques.',
    'Imagen subida correctamente': 'Image téléchargée avec succès',
    'No se pudo obtener la URL pública de la imagen.': 'Impossible d\'obtenir l\'URL publique de l\'image.',
    'Error durante la subida de imagen': 'Erreur lors du téléchargement de l\'image',
    'Producto creado correctamente': 'Produit créé avec succès',
    'Error al actualizar producto': 'Erreur lors de la mise à jour du produit',
    'Producto actualizado correctamente': 'Produit mis à jour avec succès',
    '¿Estás seguro de que deseas eliminar este producto?': 'Êtes-vous sûr de vouloir supprimer ce produit ?',
    'El producto será eliminado permanentemente de la lista de productos activos. Los pedidos históricos que contengan este producto se mantendrán intactos.': 'Le produit sera supprimé définitivement de la liste des produits actifs. Les commandes historiques contenant ce produit resteront intactes.',
    'Error al verificar el uso del producto': 'Erreur lors de la vérification de l\'utilisation du produit',
    'El producto aparece en el historial de pedidos, pero se eliminará correctamente.': 'Le produit apparaît dans l\'historique des commandes, mais sera supprimé correctement.',
    'Error al eliminar producto:': 'Erreur lors de la suppression du produit :',
    'Producto eliminado correctamente. El historial de pedidos se mantiene intacto.': 'Produit supprimé avec succès. L\'historique des commandes reste intact.',
    'Error al eliminar producto': 'Erreur lors de la suppression du produit',
    'Creando...': 'Création...',
    'Guardando cambios...': 'Enregistrement des modifications...',
    'Guardar cambios': 'Enregistrer les modifications',
    'Espera a que termine la operación': 'Attendez la fin de l\'opération',
    'Cancelar edición': 'Annuler la modification',
    'Editar producto': 'Modifier le produit',
    'Eliminar producto permanentemente': 'Supprimer le produit définitivement',

    // Category Manager
    'Gestión de Categorías': 'Gestion des Catégories',
    'Actualizar': 'Actualiser',
    'Actualizar lista': 'Actualiser la liste',
    'Editando Categoría': 'Modification de la Catégorie',
    'Nueva Categoría': 'Nouvelle Catégorie',
    'Nombre de la categoría': 'Nom de la catégorie',
    'Editando:': 'Modification :',
    'Guardando...': 'Enregistrement...',
    'Categorías Existentes': 'Catégories Existantes',
    'Error al cargar categorías:': 'Erreur lors du chargement des catégories :',
    'Error desconocido': 'Erreur inconnue',
    'Categoría actualizada correctamente': 'Catégorie mise à jour avec succès',
    'Categoría creada correctamente': 'Catégorie créée avec succès',
    'Error al guardar la categoría:': 'Erreur lors de l\'enregistrement de la catégorie :',
    '¿Estás seguro de eliminar la categoría': 'Êtes-vous sûr de vouloir supprimer la catégorie',
    'Esta acción no se puede deshacer.': 'Cette action ne peut pas être annulée.',
    'Error al verificar el uso de la categoría': 'Erreur lors de la vérification de l\'utilisation de la catégorie',
    'No se puede eliminar la categoría porque está siendo usada por': 'Impossible de supprimer la catégorie car elle est utilisée par',
    'producto(s). Elimine o reasigne los productos primero.': 'produit(s). Supprimez ou réassignez les produits d\'abord.',
    'Categoría eliminada correctamente': 'Catégorie supprimée avec succès',
    'Error al eliminar la categoría:': 'Erreur lors de la suppression de la catégorie :',
    'Cargando categorías...': 'Chargement des catégories...',
    'Modificando categoría:': 'Modification de la catégorie :',
    'Creada:': 'Créée :',
    'No hay categorías creadas': 'Aucune catégorie créée',
    'Editar categoría': 'Modifier la catégorie',
    'Eliminar categoría': 'Supprimer la catégorie',

    // User Manager
    'Gestión de Usuarios': 'Gestion des Utilisateurs',
    'Nuevo Empleado': 'Nouvel Employé',
    'Mostrar eliminados': 'Afficher les supprimés',
    'Mostrar inactivos': 'Afficher les inactifs',
    'Nombre Completo': 'Nom Complet',
    'Correo Electrónico': 'Adresse E-mail',
    'Contraseña': 'Mot de passe',
    'Teléfono': 'Téléphone',
    'Rol': 'Rôle',
    'Super Administrador': 'Super Administrateur',
    'Administrador': 'Administrateur',
    'Cajero': 'Caissier',
    'Barista': 'Barista',
    'Camarero': 'Serveur',
    'Crear Empleado': 'Créer un Employé',
    'Empleado': 'Employé',
    'Contacto': 'Contact',
    'Correo': 'E-mail',
    'Activo': 'Actif',
    'Inactivo': 'Inactif',
    'Eliminado': 'Supprimé',
    'Solo un Super Administrador puede crear otros Super Administradores': 'Seul un Super Administrateur peut créer d\'autres Super Administrateurs',
    'No se pudo crear el usuario': 'Impossible de créer l\'utilisateur',
    'Empleado creado exitosamente. Si la confirmación por email está habilitada, el usuario debe confirmar su correo.': 'Employé créé avec succès. Si la confirmation par e-mail est activée, l\'utilisateur doit confirmer son adresse e-mail.',
    'Error al crear empleado': 'Erreur lors de la création de l\'employé',
    'Usuario': 'Utilisateur',
    'desactivado': 'désactivé',
    'activado': 'activé',
    'Error al actualizar estado del empleado': 'Erreur lors de la mise à jour du statut de l\'employé',
    'Correo actualizado': 'E-mail mis à jour',
    'No se pudo actualizar el correo': 'Impossible de mettre à jour l\'e-mail',
    'Este usuario no tiene correo guardado': 'Cet utilisateur n\'a pas d\'e-mail enregistré',
    'Email de restablecimiento enviado': 'E-mail de réinitialisation envoyé',
    'No se pudo enviar el email de restablecimiento': 'Impossible d\'envoyer l\'e-mail de réinitialisation',
    'Eliminar lógicamente a': 'Supprimer logiquement',
    'Usuario eliminado (borrado lógico)': 'Utilisateur supprimé (suppression logique)',
    'No se pudo eliminar el usuario': 'Impossible de supprimer l\'utilisateur',
    'Error al cargar empleados': 'Erreur lors du chargement des employés',
    'No registrado': 'Non enregistré',
    'correo@ejemplo.com': 'email@exemple.com',
    'Usuario eliminado': 'Utilisateur supprimé',
    'Editar correo': 'Modifier l\'e-mail',
    'Guardar correo': 'Enregistrer l\'e-mail',
    'Enviar reset de contraseña': 'Envoyer la réinitialisation du mot de passe',
    'Sin correo': 'Sans e-mail',
    'Desactivar': 'Désactiver',
    'Activar': 'Activer',
    'Reset': 'Réinitialiser',
    'Guardar': 'Enregistrer',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('es');

  // Cargar idioma guardado al iniciar
  useEffect(() => {
    const savedLanguage = localStorage.getItem('app-language') as Language;
    if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'fr')) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('app-language', lang);

    // Actualizar idioma del documento
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key as keyof typeof translations.es] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}